// WaterPulse 프로젝트 허브 내용. 화면(hub.js)은 이 파일과 status.json(수집 현황)만 읽는다.
// 상태: done 끝남 · doing 진행 중 · todo 할 일 · decide 결정 필요 · wait 대기(앞 단계가 끝나야 시작)
// 내용을 고치면 UPDATED도 바꾼다.

export const UPDATED = "2026-10-10 23:40";
export const MIDTERM = { date: "2026-10-19", label: "중간발표 제출", time: "14:00" };
export const FINAL = { date: "2026-12-07", label: "최종발표 제출", time: "14:00" };

const GH = "https://github.com/keemlogan/waterpulse/blob/main/";
const L = {
  overview: { label: "WaterPulse 한눈에 보기", sub: "과제 해설·도구 설명 · 23쪽", href: "docs/overview.pdf", kind: "문서" },
  sim: { label: "실데이터 사전 시뮬레이션 보고서", sub: "로컬에서 한 바퀴 돌려 본 결과 · 18쪽", href: "docs/simulation.pdf", kind: "문서" },
  dash: { label: "방류 계산기·재난 상황판 제작 보고서", sub: "계산식·검증 · 22쪽", href: "docs/dashboard.pdf", kind: "문서" },
  webIndex: { label: "분석 결과 화면", sub: "시제품", href: "../", kind: "화면" },
  webRelease: { label: "방류 계산기", sub: "시제품 · 과거 큰비 되감기", href: "../release.html", kind: "화면" },
  webAlert: { label: "재난 상황판", sub: "시제품 · 과거 큰비 되감기", href: "../alert.html", kind: "화면" },
  collector: { label: "원본 수집기 collect_raw.py", sub: "지금 맥미니에서 도는 코드", href: GH + "code/collector/collect_raw.py", kind: "코드" },
  verify: { label: "원본 검사기 verify_raw.py", sub: "빠진 파일·중복·줄 수 검사", href: GH + "code/collector/verify_raw.py", kind: "코드" },
  etl: { label: "정제 etl_spark.py", sub: "시뮬레이션 때 쓴 Spark 정제", href: GH + "code/sim/etl_spark.py", kind: "코드" },
  analyze: { label: "분석 analyze.py", sub: "반응 시간·예측 모델", href: GH + "code/sim/analyze.py", kind: "코드" },
  scen: { label: "큰비 되감기 scenarios.py", sub: "방류·경보 시나리오", href: GH + "code/sim/scenarios.py", kind: "코드" },
  common: { label: "방류·경보 계산 common.js", sub: "두 화면이 같이 쓰는 계산", href: GH + "common.js", kind: "코드" },
  flume: { label: "적재 흉내 flume_sim.py", sub: "시뮬레이션 때 쓴 Flume 흉내", href: GH + "code/sim/flume_sim.py", kind: "코드" },
  portal: { label: "공공데이터포털", sub: "data.go.kr", href: "https://www.data.go.kr", kind: "외부" },
};

// 단계. 로드맵이 이 순서로 보인다.
export const PHASES = [
  { id: "p0", no: "0", name: "준비", what: "역할, VM을 돌릴 PC, 인증키", range: "10/10 – 10/13" },
  { id: "p1", no: "1", name: "원본 수집", what: "공공 API 5종을 받은 그대로 파일로 저장", range: "10/10 – 10/14" },
  { id: "p2", no: "2", name: "하둡에 올리기", what: "원본을 VM의 HDFS에 넣고 Hive 표 걸기", range: "10/13 – 10/16" },
  { id: "p3", no: "3", name: "정제", what: "Spark로 연도·24시·쉼표·이상값 고치기", range: "10/14 – 11/06" },
  { id: "p4", no: "4", name: "표 만들기·조회", what: "Parquet·파티션 표, Impala 조회와 효율 측정", range: "10/15 – 11/06" },
  { id: "p5", no: "5", name: "분석", what: "유입량 예측 → 방류량 계산 → 경보 채점", range: "11/03 – 11/23" },
  { id: "p6", no: "6", name: "웹 화면", what: "방류 계산기 + 재난 상황판", range: "11/17 – 11/30" },
  { id: "m1", no: "★", name: "중간발표", what: "영상 약 10분 · 슬라이드 · 보충 자료", range: "10/19 14:00 마감", milestone: true },
  { id: "m2", no: "★", name: "최종발표", what: "영상 약 15분 · 소스코드·매뉴얼 압축 파일", range: "12/07 14:00 마감", milestone: true },
];

// 첫 화면 맨 위 문장
export const HERO = { title: "원본 데이터를 모으고 있어요", sub: "그동안 VM을 돌릴 PC를 정하고 중간발표 준비를 시작해야 해요." };

// 로드맵에서 처음부터 펼쳐 둘 단계(지금 하는 단계와 가까운 마감)
export const CURRENT = ["p0", "p1", "m1"];

// 첫 화면 "지금 할 일"에 올릴 순서
export const NOW = ["T02", "T03", "T01", "T11", "T70", "T71"];
export const RECENT = [
  { d: "10/10", t: "원본 전체 수집 시작 — 맥미니에서 키 3개로, 10/12 끝날 예정" },
  { d: "10/10", t: "관측소 자료가 해마다 1시간씩 빠지는 문제를 찾아 고침(703개 파일 보충)" },
  { d: "10/10", t: "최종 목표 확정 — 방류 계산기와 재난 상황판 둘 다" },
];

export const TASKS = [
  // ───────────── 0. 준비 ─────────────
  { id: "T01", phase: "p0", status: "decide", due: "2026-10-11", title: "역할 나누기",
    lead: "네 줄기로 나눠 서로 겹치지 않게 일해요.",
    why: "단계마다 쓰는 도구가 달라요(수집기, 하둡, Spark, 웹). 한 사람이 한 줄기를 끝까지 맡으면 넘겨주는 비용이 줄고, 최종 채점의 '개인 기여'도 분명해져요.",
    how: ["아래 네 줄기 중 하나씩 맡아요. 인원이 3명이면 ①과 ②를 합쳐요.",
      "① 수집·적재: 수집기, 원본 검사, HDFS에 올리기, Flume",
      "② 하둡 표·DB: Hive·Impala 표, Sqoop, MySQL",
      "③ 정제·분석: Spark 정제, 예측 모델, 방류·경보 검증",
      "④ 웹·발표: 두 화면, 슬라이드, 영상 편집",
      "정해지면 이 허브의 각 할 일에 담당자 이름을 적어요(data.js의 owner)."],
    done: [["네 줄기마다 담당자가 정해짐", false], ["허브 할 일마다 담당자 이름이 보임", false]],
    now: "아직 정하지 않았어요." },
  { id: "T02", phase: "p0", status: "decide", due: "2026-10-12", title: "VM을 돌릴 PC 정하기",
    lead: "수업 VM은 인텔·AMD(x86) PC에서만 제대로 돌아요. 맥북·맥미니로는 안 돼요.",
    why: "최종 결과는 '수업 실습 VM 같은 표준 환경에서 재현'돼야 해요. 수업 VM(Cloudera)은 x86용이라 애플 M 칩 맥에서는 켜지지 않거나 너무 느려요. 그래서 팀원 중 한 명의 x86 PC를 '본 VM' 자리로 정해야 해요.",
    how: ["팀원마다 PC를 확인해요: CPU 종류(인텔·AMD인지 애플 M인지), 메모리, SSD 여유 공간.",
      "조건(메모리 16GB 이상, SSD 여유 100GB 이상, BIOS 가상화 켜짐)에 맞는 PC 한 대를 본 VM으로 정해요.",
      "그 PC는 작업 기간에 켜 두고 잠자기를 꺼요.",
      "다른 팀원은 Tailscale로 그 PC의 Hue 화면(8888번)에 들어와 같이 봐요. 방법은 VM 가이드에 있어요."],
    done: [["본 VM PC가 정해지고 사양이 기록됨", false], ["다른 팀원이 원격으로 Hue에 들어가 봄", false]],
    now: "팀원 PC 사양을 모으는 중이에요. 맥북(M2)·맥미니(M4)는 후보가 아니에요.",
    links: [{ label: "VM 가이드", sub: "왜 x86이어야 하나·권장 사양·같이 보는 방법", href: "#/t/G1", kind: "가이드" }] },
  { id: "T03", phase: "p0", status: "todo", due: "2026-10-12", title: "교수님께 VM 질문 보내기",
    lead: "VM 이미지와 재현 환경 기준이 정해져야 하둡 작업 계획이 확정돼요.",
    why: "강의 자료에는 VM을 받는 곳, 버전, 사양이 나오지 않아요. 과제 설명서에도 '표준 환경(예: 수업 실습 VM)'이라는 한 줄뿐이에요. 잘못 짐작하고 진행하면 최종 재현에서 막혀요.",
    how: ["아래 여섯 가지를 e-class 질문 게시판이나 메일로 보내요(중요한 순서).",
      "① VM 이미지는 어디서 받고, 버전과 안의 Spark·Python 버전은 무엇인가요?",
      "② 최종 재현은 꼭 그 VM이어야 하나요? 같은 도구의 다른 환경(Docker·클라우드·다른 버전)도 되나요?",
      "③ 애플 M 칩 맥을 쓰는 학생은 어떻게 하라는 공식 안내가 있나요?",
      "④ VM 안에 scikit-learn·Flask·새 Python을 더 설치해도 되나요?",
      "⑤ 원본 약 15GB를 Google Drive에 통째로 내야 하나요, 샘플과 수집 스크립트면 되나요?",
      "⑥ 중간발표 '중간 결과'는 VM의 HDFS·Hive에서 돌린 것이어야 하나요, 로컬 Spark 결과도 되나요?"],
    done: [["질문을 보냄", false], ["답을 받아 허브에 반영함", false]],
    now: "질문 목록만 정리돼 있어요." },
  { id: "T04", phase: "p0", status: "wait", due: "2026-10-13", title: "수업 VM 설치하고 버전 확인하기",
    lead: "본 VM PC에 이미지를 설치하고, 안에 든 도구 버전을 적어 둬요.",
    why: "Spark·Python 버전에 따라 쓸 수 있는 문법과 라이브러리가 달라요. 시뮬레이션 코드는 Spark 4로 짰기 때문에, VM 버전이 낮으면 일부를 고쳐야 해요.",
    how: ["VirtualBox 또는 VMware Workstation을 설치하고 이미지를 불러와요. VM 메모리는 8GB로 잡아요.",
      "VM 안 터미널에서 아래 명령을 실행해 결과를 이 카드에 적어요.",
      "브라우저로 Hue(보통 8888번)에 들어가 HDFS 파일 화면이 열리는지 봐요."],
    code: "hadoop version\nhive --version\nimpala-shell --version\nspark-submit --version\npython3 --version\nmysql --version; sqoop version; flume-ng version\ndf -h; free -g",
    done: [["VM이 켜지고 Hue가 열림", false], ["도구 버전표가 기록됨", false]],
    now: "VM 이미지를 받는 곳이 확인되면(T03) 시작해요." },
  { id: "T05", phase: "p0", status: "done", title: "공공데이터 인증키 3개 확보",
    lead: "내 키 + 팀원 키 2개. 5개 API 모두 신청·호출 확인을 끝냈어요.",
    why: "공공데이터포털은 키마다, 기능마다 하루 10,000번까지만 부를 수 있어요. 키가 3개면 하루에 받을 수 있는 양이 3배라 수집이 8일에서 3일로 줄어요.",
    how: ["각자 data.go.kr에서 5개 API를 활용신청했어요: 수문 운영 정보(15099110), 댐코드(15099105), 우량수위 관측소(15099115), 수문 제원(15099107), 기상청 ASOS 시간자료(15057210).",
      "10/10 맥북에서 키마다 5개 API를 한 번씩 불러 모두 정상 응답을 확인했어요.",
      "키는 맥미니 ~/WaterPulse/.env 에만 있고 저장소에는 올리지 않아요."],
    done: [["키 3개 확보", true], ["5개 API 호출 확인", true]],
    now: "끝났어요. 키가 더 생기면 .env에 한 줄 추가하고 수집기를 다시 시작하면 돼요.",
    links: [L.portal] },

  // ───────────── 1. 원본 수집 ─────────────
  { id: "T10", phase: "p1", status: "done", title: "수집기 만들기",
    lead: "받은 값을 고치지 않고 그대로 저장하는 프로그램이에요.",
    why: "원본을 그대로 남겨야 정제 규칙이 틀렸을 때 다시 받지 않고 고칠 수 있어요. 또 '하둡 안에서 고쳤다'는 과정 자체가 최종 채점의 관리·디버깅 근거가 돼요.",
    how: ["자료 종류(기능)마다 할 일 목록을 만들고, 최근 연도부터 받아요.",
      "키·기능마다 하루 호출 수를 세다가 한도에 닿으면 그 일꾼만 자정까지 쉬어요. 세 키가 같은 목록을 나눠 받아서 같은 작업을 두 번 받지 않아요.",
      "한 번에 받는 줄 수를 지켜요(댐 400 · 관측소 500 · ASOS 999). 넘기면 오류 없이 빈 답이 와요.",
      "줄마다 조회 조건만 덧붙여요: q_damcode(댐), q_stn(관측소·지점), q_from·q_to(기간). 값은 그대로예요.",
      "끊겨도 다시 실행하면 받은 파일은 건너뛰고 이어 받아요. 오류로 멈추면 1분 뒤 자동으로 다시 떠요."],
    done: [["5개 기능 모두 시험 통과(받은 줄 수 = 전체 건수)", true], ["맥미니에서 실행", true]],
    now: "끝났어요. 10/10 관측소 24시 문제를 고친 판이 돌고 있어요.",
    links: [L.collector, L.verify] },
  { id: "T11", phase: "p1", status: "doing", due: "2026-10-12", title: "원본 전체 받기", live: true,
    lead: "맥미니에서 키 3개로 받는 중이에요. 10/12(월)에 끝날 예정이에요.",
    why: "분석과 경보 검증에는 2006년부터의 긴 기록이 필요해요. 큰비는 드물어서, 기간이 길수록 '큰물 때 예측이 맞는지'를 제대로 잴 수 있어요.",
    how: ["범위: 댐 59곳 시간·일 자료, 상류 비 관측소 187곳·강 관측소 244곳 시간 자료, 기상청 ASOS 전국 100곳 시간 자료. 기간은 모두 2006-01-01 ~ 2026-10-09.",
      "댐 10분 자료는 받지 않아요. 1시간 자료로 충분하고, 받으면 수집 기간이 두 배 넘게 늘어요.",
      "2006년 전 관측소 자료도 받지 않아요. 짝지을 댐 자료가 2006년부터만 있어요.",
      "현황은 맥미니에서 ~/WaterPulse/status.sh 로 보거나, 이 허브 첫 화면에서 봐요(갱신 시각 확인)."],
    table: { head: ["자료", "예상 행 수", "예상 용량"], rows: [["댐 시간", "약 989만", "1.4GB"], ["댐 일", "약 41만", "0.1GB"], ["비 관측소", "약 3,315만", "2.4GB"], ["강 관측소", "약 2,790만", "2.0GB"], ["ASOS", "약 1,821만", "9.3GB"], ["합계", "약 8,960만", "약 15GB"]] },
    done: [["다섯 자료 모두 받아야 할 파일 수만큼 받음", false], ["검사에서 빠진 파일 0", false]],
    now: "위 수집 현황 카드가 지금 상태예요. 맥미니 검사 결과를 허브에 옮길 때마다 갱신돼요(갱신 시각 확인)." },
  { id: "T12", phase: "p1", status: "doing", title: "받은 원본 검사하기",
    lead: "빠진 파일, 줄 수 부족, 같은 시각 중복, 마지막 24시 줄을 검사해요.",
    why: "수집기가 조용히 데이터를 빠뜨리면 분석이 틀어져도 알아채기 어려워요. 검사 결과는 발표의 '예외 처리' 근거가 돼요.",
    how: ["맥미니에서 verify_raw.py를 실행하면 자료별 결과가 state/verify.json에 남아요. 수집이 다 끝나면 자동으로 한 번 돌아요.",
      "10/10에 찾은 문제: 관측소 API는 하루를 01~24시로 적어서, 끝 시각을 23시로 넣으면 매년 '12월 31일 24시'가 빠졌어요. 끝 시각을 24시로 바꾸고, 이미 받은 703개 파일에 빠진 한 줄을 채웠어요."],
    done: [["중복 시각 0", true], ["줄 수 부족 0", true], ["전체 수집 후 빠진 파일 0", false]],
    now: "10/10 23:03 검사: 받은 2,799개 파일에서 중복 0, 줄 수 부족 0. 24시 줄이 없는 파일 1개는 원본에 그 시각 자료가 없는 것으로 보여요.",
    links: [L.verify] },
  { id: "T13", phase: "p1", status: "todo", due: "2026-10-14", title: "기준표 만들기 (MySQL)",
    lead: "API로 받지 못하는 정보를 작은 표로 만들어 MySQL에 넣어요.",
    why: "댐 좌표, 댐과 관측소·ASOS 지점의 연결, 수위↔저수량 곡선은 분석에 꼭 필요한데 API에 없거나 흩어져 있어요. MySQL에 두고 Sqoop으로 하둡에 가져오면 수업의 Sqoop import를 자연스럽게 쓰는 자리가 돼요.",
    how: ["dam: 댐코드·이름·종류·좌표·유역 넓이·계획홍수위·관리 기준 수위 (좌표는 공개 자료로 직접 입력)",
      "station_dam: 댐-관측소 연결 (수집 때 받은 관측소 목록을 그대로 씀, 시험용 관측소 표시)",
      "asos_dam: 댐마다 가까운 ASOS 1~3곳과 거리 (지점 좌표는 기상청 지점 정보)",
      "level_curve: 댐별 수위↔저수량 곡선 (시간 자료의 수위·저수량 쌍으로 만듦)",
      "CSV로 채워 MySQL에 LOAD DATA로 넣어요."],
    done: [["표 4개가 MySQL에 있음", false], ["댐 59곳 좌표가 채워짐", false]],
    now: "관측소 목록은 수집 때 받아 둬서 station_dam은 바로 만들 수 있어요." },
  { id: "T14", phase: "p1", status: "wait", title: "원본 압축 백업",
    lead: "다 받으면 압축해서 공유 드라이브에 올려요.",
    why: "맥미니 한 대에만 있으면 고장이나 실수에 약해요. 이 압축본이 최종 제출의 '데이터 얻는 법·스냅샷'이 되기도 해요.",
    how: ["수집과 검사가 끝나면 raw 폴더를 자료별로 압축해요(JSON은 압축하면 크게 줄어요).", "공유 드라이브에 올리고 링크를 이 카드에 적어요."],
    done: [["압축본이 공유 드라이브에 있음", false]],
    now: "수집이 끝나면(T11) 시작해요." },

  // ───────────── 2. 하둡에 올리기 ─────────────
  { id: "T20", phase: "p2", status: "wait", title: "HDFS 폴더 만들고 원본 올리기",
    lead: "받은 원본을 VM의 HDFS '원본 선반'에 그대로 올려요.",
    why: "과제가 말하는 '저장'은 하둡에 넣는 거예요(예시: load them into HDFS). 여기부터 빅데이터 관리 채점이 시작돼요.",
    how: ["폴더는 수업 규칙대로 작업 중은 /etl, 완성본은 /data 에 둬요.",
      "원본 파일을 VM 공유 폴더로 옮긴 뒤 hdfs dfs -put 으로 올려요(Flume을 배운 뒤에는 T23).",
      "올린 뒤 hdfs dfs -du 로 용량이 맞는지 확인해요."],
    code: "/etl/waterpulse/raw/{dam_hourly,dam_daily,rain_hourly,level_hourly,asos_hourly,meta}/   ← 받은 그대로\n/data/waterpulse/clean/…/year=YYYY/   ← 정제한 Parquet\n/data/waterpulse/ref/…                ← Sqoop으로 가져온 기준표\n/data/waterpulse/mart/…               ← 분석 결과\n\nhdfs dfs -mkdir -p /etl/waterpulse/raw/dam_hourly\nhdfs dfs -put dam_hourly/*.jsonl /etl/waterpulse/raw/dam_hourly/\nhdfs dfs -du -h /etl/waterpulse/raw",
    done: [["원본 다섯 종이 HDFS에 있음", false], ["용량이 맥미니 원본과 같음", false]],
    traps: ["작은 파일이 너무 많으면 HDFS가 비효율적이에요(파일 1만 개 넘음). 정제 단계에서 Spark가 큰 Parquet 파일로 합쳐요."],
    now: "VM이 준비되면(T04) 시작해요. 중간발표용으로는 샘플만 먼저 올려요(T70)." },
  { id: "T21", phase: "p2", status: "wait", title: "Hive 원본 표 만들기",
    lead: "원본 폴더에 표 이름표만 붙여요. 모든 칸을 글자(STRING)로 둬요.",
    why: "Hive는 읽을 때 형식을 확인해서, \"1,857.835\" 같은 값을 숫자 칸으로 읽으면 조용히 빈칸(NULL)이 돼요. 시뮬레이션에서 그냥 숫자로 읽었더니 저수량 13만 칸이 사라졌어요. 그래서 원본 표는 글자로 걸고, 숫자 변환은 Spark가 해요.",
    how: ["EXTERNAL 표로 만들어요. 표를 지워도 원본 파일은 남아요.", "줄마다 JSON 한 건이라 JSON SerDe로 바로 읽혀요.", "SELECT COUNT(*) 결과가 검사기의 행 수와 같은지 확인해요."],
    code: "CREATE DATABASE IF NOT EXISTS wp;\nCREATE EXTERNAL TABLE wp.raw_dam_hourly (\n  q_damcode STRING, q_from STRING, q_to STRING,\n  obsrdt STRING, inflowqy STRING, totdcwtrqy STRING, rsvwtqy STRING,\n  rsvwtrt STRING, lowlevel STRING, rf STRING)\nROW FORMAT SERDE 'org.apache.hive.hcatalog.data.JsonSerDe'\nLOCATION '/etl/waterpulse/raw/dam_hourly';\nSELECT COUNT(*) FROM wp.raw_dam_hourly;",
    done: [["원본 표 다섯 개", false], ["행 수가 검사 결과와 같음", false]],
    traps: ["JsonSerDe jar 위치는 VM 버전마다 달라요(T04에서 확인)."] },
  { id: "T22", phase: "p2", status: "wait", title: "기준표 가져오기 (Sqoop import)",
    lead: "MySQL 기준표 4개를 Hive로 가져와요.",
    why: "수업에서 배운 Sqoop import를 실제 데이터에 쓰는 자리예요. 기준표는 작아서 병렬 작업 1개면 충분해요.",
    how: ["표마다 아래 명령을 한 번씩 실행해요.", "VM MySQL 계정은 매뉴얼에 적되 저장소에는 올리지 않아요."],
    code: "sqoop import \\\n  --connect jdbc:mysql://localhost/waterpulse_ref \\\n  --username <VM 계정> -P \\\n  --table station_dam \\\n  --hive-import --hive-table wp.ref_station_dam -m 1",
    done: [["기준표 4개가 Hive에 있음", false]] },
  { id: "T23", phase: "p2", status: "wait", title: "Flume으로 자동 적재",
    lead: "수집기가 떨군 파일을 Flume이 HDFS로 옮기게 해요.",
    why: "과제 예시의 '주기적 수집 → 적재' 구조를 수업 도구로 보여 주는 자리예요. Flume 강의를 들은 뒤 설정을 확정해요.",
    how: ["spooldir 소스가 폴더를 지켜보다가 새 파일을 HDFS 원본 선반으로 옮겨요.", "rollSize를 128MB로 잡아 작은 파일을 줄여요.", "수집기는 다 쓴 파일만 보이게(임시 이름 → 이름 바꾸기) 이미 만들어 뒀어요."],
    code: "a1.sources = raw\na1.channels = c1\na1.sinks = k1\na1.sources.raw.type = spooldir\na1.sources.raw.spoolDir = /home/<계정>/waterpulse/spool/dam_hourly\na1.channels.c1.type = file\na1.sinks.k1.type = hdfs\na1.sinks.k1.hdfs.path = /etl/waterpulse/raw/dam_hourly\na1.sinks.k1.hdfs.fileType = DataStream\na1.sinks.k1.hdfs.rollSize = 134217728\na1.sources.raw.channels = c1\na1.sinks.k1.channel = c1",
    done: [["설정 파일로 한 종류 이상 자동 적재", false]],
    now: "Flume 강의 뒤에 시작해요. 위 설정은 초안이에요.", links: [L.flume] },

  // ───────────── 3. 정제 ─────────────
  { id: "T30", phase: "p3", status: "wait", title: "Spark로 정제하기",
    lead: "원본 표를 읽어 고친 '정리본'을 Parquet으로 새로 써요. 원본은 그대로 둬요.",
    why: "자료마다 함정이 달라요. 이걸 하둡 안에서 고쳐야 '데이터 관리 깊이'와 '디버깅 과정'이 증거로 남고, VM에서 그대로 재현돼요.",
    how: ["아래 규칙표대로 고치고, 고친 개수를 출력해요.", "Spark 설정: spark.sql.ansi.enabled=false (Hive처럼 NULL로), spark.sql.warehouse.dir를 임시 폴더로.", "결과는 연도별 폴더(파티션)로 나눠 Parquet으로 저장해요."],
    table: { head: ["자료", "원본 모양", "처리"], rows: [
      ["댐", "\"01-14 01시\" (연도 없음)", "q_from의 연도를 붙임"],
      ["댐", "\"01-01 24시\"", "다음 날 00시로"],
      ["댐", "\"1,857.835\", 같은 칸에 숫자·글자 섞임", "쉼표 빼고 숫자로"],
      ["댐", "유입량 0 이하 (계산값이라)", "표시 열 + 학습은 지난 3시간 양수 평균"],
      ["댐", "유입량 4,223만 ㎥/s 같은 값", "댐 상위 0.1%의 10배 넘고 앞뒤 시간의 10배 넘으면 NULL"],
      ["관측소", "\"2025-12-31 24:00\" (01~24시 표기)", "다음 날 00:00으로"],
      ["관측소", "시험용 관측소", "제외"],
      ["ASOS", "강수량 빈칸", "품질 표시도 빈칸이면 0mm, 표시가 9면 결측"],
      ["공통", "자료가 없는 시간", "1시간 격자로 빈칸을 드러냄(비 안 온 것과 구분)"]] },
    done: [["다섯 자료의 정리본 Parquet", false], ["규칙별 고친 개수 기록", false]],
    traps: ["Spark가 쓴 Parquet은 댐 안에서도 시간순이 아니에요. 'N행 뒤'가 아니라 '시각 + N시간'으로 찾아야 해요(시뮬레이션에서 9시간 예측 정답이 이것 때문에 틀렸어요)."],
    links: [L.etl] },
  { id: "T31", phase: "p3", status: "wait", title: "데이터 품질표 만들기",
    lead: "댐·관측소별 기간, 빈칸 비율, 이상값 비율, 고친 개수를 한 표로.",
    why: "중간 채점의 '예외 상황까지 생각했나'에 대한 직접 증거예요. 발표에 한 장 넣어요.",
    how: ["정제 작업이 고친 개수를 같이 내도록 하고, 자료별로 모아 표 하나로 만들어요."],
    done: [["품질표 한 장", false]],
    now: "시뮬레이션 예: 소양강 52,608시간 중 빈칸 0%, 0 이하 유입 29.8%." },

  // ───────────── 4. 표 만들기·조회 ─────────────
  { id: "T40", phase: "p4", status: "wait", title: "정리본 표 만들기 (Parquet · 연도 파티션)",
    lead: "Spark가 쓴 정리본 폴더에 Hive 표를 걸어요.",
    why: "파티션으로 나누면 '2023년만' 같은 질문에 그 칸만 읽어 빨라져요. Parquet은 용량이 작고 필요한 열만 읽어요. 둘 다 '효율적 관리'의 근거예요.",
    how: ["연도로만 나눠요. 댐×날짜처럼 잘게 나누면 작은 파일 문제가 다시 생겨요.", "MSCK REPAIR TABLE로 폴더의 파티션을 표에 등록해요."],
    code: "CREATE EXTERNAL TABLE wp.dam_hourly (\n  damcode STRING, ts TIMESTAMP, inflow DOUBLE, outflow DOUBLE,\n  storage DOUBLE, storage_pct DOUBLE, level_m DOUBLE, rain_mm DOUBLE, inflow_le0 BOOLEAN)\nPARTITIONED BY (year INT) STORED AS PARQUET\nLOCATION '/data/waterpulse/clean/dam_hourly';\nMSCK REPAIR TABLE wp.dam_hourly;",
    done: [["정리본 표 다섯 개", false]],
    traps: ["Parquet의 시각은 도구에 따라 9시간 밀려 보일 수 있어요. 같은 행을 Spark와 Impala로 한 번씩 조회해 맞춰 봐요."] },
  { id: "T41", phase: "p4", status: "wait", title: "Impala로 조회하고 효율 재기",
    lead: "같은 질문을 형식·파티션만 바꿔 재서 숫자로 보여 줘요.",
    why: "최종 채점에 '관리 도구 선택의 효율성과 적절성'이 있어요. 말보다 전후 숫자가 설득력 있어요.",
    how: ["새 표는 INVALIDATE METADATA, 새 데이터는 REFRESH 를 먼저 실행해요.", "측정 질문(예: 2023년 7월 소양강 시간별 유입량)을 원본(JSON) 표와 정리본(Parquet·파티션) 표에서 각각 3번 재서 가운데 값을 써요.", "용량은 hdfs dfs -du 로 비교해요."],
    table: { head: ["비교", "재는 것", "시뮬레이션 참고값"], rows: [["JSON → Parquet", "용량", "댐 시간 자료 429MB → 47MB"], ["파티션 없음 → 연도 파티션", "조회 시간", "VM에서 측정"], ["Hive ↔ Impala", "응답 시간", "VM에서 측정"]] },
    done: [["비교 3가지 측정값과 캡처", false]] },
  { id: "T42", phase: "p4", status: "wait", title: "결과 표 내보내기 (Sqoop export → MySQL)",
    lead: "웹이 읽을 결과 표를 MySQL로 보내요.",
    why: "수업 Sqoop export 예제와 같은 구조예요. 웹 서버는 MySQL만 읽으면 돼요.",
    how: ["Spark가 결과를 CSV 폴더로도 한 벌 써요(export는 텍스트가 쉬워요).", "MySQL에 받을 표를 먼저 만들어 둬요.", "결과 표: forecast(예측) · release(방류) · alert(경보) · lag_events(반응 시간) · quality(품질)."],
    code: "sqoop export \\\n  --connect jdbc:mysql://localhost/waterpulse_web \\\n  --username <VM 계정> -P --table forecast \\\n  --export-dir /data/waterpulse/mart/forecast_csv \\\n  --input-fields-terminated-by ','",
    done: [["결과 표 다섯 개가 MySQL에 있음", false]] },

  // ───────────── 5. 분석 ─────────────
  { id: "T50", phase: "p5", status: "doing", title: "반응 시간 분석",
    lead: "비가 가장 많이 온 시각부터 댐 유입이 가장 많은 시각까지, 몇 시간 걸리나.",
    why: "과제가 원하는 '비교 분석'이에요. 또 예측 모델이 '몇 시간 전 비까지 볼지' 정하는 근거가 돼요.",
    how: ["큰비 사건(6시간에 20mm 이상)을 잘라 사건마다 잰 뒤 댐별 가운데 값을 내요.", "유역 넓이와 비교하고, 20년 동안 변했는지 봐요.", "전체 데이터(2006~)로 다시 돌려요."],
    done: [["시뮬레이션(2020~2025) 결과", true], ["전체 데이터로 다시 낸 결과", false]],
    now: "시뮬레이션 결과: 가운데 값 10시간, 유역이 넓을수록 느림(순위 상관 0.89, 댐 35곳), 20년 추세는 없음.",
    links: [L.analyze, L.webIndex] },
  { id: "T51", phase: "p5", status: "doing", title: "유입량 예측 모델 (기본)",
    lead: "3·6·12시간 뒤 댐에 들어올 물을 맞혀요. 방류 계산기와 재난 상황판이 같이 써요.",
    why: "두 화면 모두 이 예측을 입력으로 써요. 예측이 약하면 둘 다 약해져요.",
    how: ["학습표: 한 줄 = 한 댐의 한 시각. 지난 비·지난 유입·저수율·달력 → 정답은 몇 시간 뒤 유입(Spark로 만듦).", "모델: scikit-learn 그래디언트 부스팅, 댐·시간별로 따로(과제가 Python을 허용해요).", "앞 해로 배우고 뒤 해로 시험해요(섞으면 미래를 미리 본 셈).", "채점: '몇 시간 뒤에도 지금 그대로'라고 찍는 기준선보다 오차가 몇 % 줄었나. 큰물 때만 따로도 계산해요."],
    done: [["시뮬레이션 모델", true], ["전체 데이터 모델", false]],
    now: "시뮬레이션: 6시간 뒤 기준선보다 10% 나음, 큰물 때 17% 나음. 물이 두 배 넘게 불 때는 실제보다 낮게(45~68%) 나와요. 주원인은 앞으로 올 비를 모른다는 것.",
    links: [L.analyze, L.sim] },
  { id: "T52", phase: "p5", status: "todo", due: "2026-11-16", title: "관측소·ASOS로 예측 정확도 올리기",
    lead: "입력을 한 묶음씩 더하며 무엇이 얼마나 도움이 되는지 숫자로 남겨요.",
    why: "'분석의 깊이' 채점 항목이에요. 상류 관측소는 비가 댐에 닿기 전 강에서 먼저 불어나는 걸 보여 주고, ASOS는 땅이 젖은 정도(최근 며칠 비)와 눈 녹는 시기(기온)를 더해 줘요.",
    how: ["같은 시험 기간·같은 채점으로 아래 다섯 단계를 차례로 재요.", "대상: 관측소가 많은 댐(소양강·대청·안동·용담·남강·섬진강)과 관측소가 없는 댐(영주·성덕·보현산)을 따로 묶어요.", "마지막에 방류 계산기·재난 상황판까지 이어서 재요: 운영자보다 먼저 알린 횟수(지금 107번 중 46번)가 늘어나는가."],
    table: { head: ["단계", "입력", "기대"], rows: [["M0 기준선", "지금 그대로", "비교의 바닥"], ["M1 댐만", "댐 유입·강우·저수율·달력", "시뮬레이션 개선률 0.10~0.22"], ["M2 + 상류 관측소", "상류 비·강 수위·유량", "개선(대청 12시간 큰물 0.15 → 0.25, 시뮬레이션 3개 댐)"], ["M3 + ASOS", "최근 3·7·30일 비, 기온·습도·적설", "작게 개선 예상 → 실험으로 확인"], ["M4 상한", "앞으로 실제로 내린 비까지", "미래 비를 알면 얼마나 좋아지나의 천장"]] },
    done: [["다섯 단계 비교표", false], ["경보 선행 횟수 비교", false]],
    traps: ["시험 기간에 큰비가 적으면 개선이 우연일 수 있어요. 큰물 시간 수를 항상 같이 적어요."] },
  { id: "T53", phase: "p5", status: "doing", title: "방류 계산 검증",
    lead: "계산기 답이 실제 운영과 비슷한 크기인지 확인해요.",
    why: "방류 계산기가 '그럴듯한 숫자'를 내는지 증명해야 해요. 오차를 계산식 탓과 예측 탓으로 나눠 보여 줘요.",
    how: ["실제 유입·방류를 넣었을 때 계산식만의 수위 오차를 재요.", "예측 유입을 넣었을 때 오차를 재요.", "'더 내보내라'고 한 때 실제 운영 방류와 비교해요."],
    done: [["시뮬레이션 검증", true], ["전체 데이터 검증", false]],
    now: "시뮬레이션: 계산식만의 오차 평균 7cm, 예측을 넣으면 43cm(물이 불 때 78cm 낮게). '더 내보내라' 답은 실제 운영의 1.01배(184번).",
    links: [L.dash, L.common] },
  { id: "T54", phase: "p5", status: "doing", title: "재난 경보 채점",
    lead: "운영자가 방류를 늘리기 전에 경계·위험을 먼저 켰는지로 채점해요.",
    why: "운영자가 개입하기 때문에 '실제로 넘쳤나'로 채점하면 안 맞아요. 대신 '사람보다 먼저 알았나'를 봐요.",
    how: ["큰비 사건마다 시각을 되감아 경보를 켜고, 운영자 방류 증가 시각과 비교해요.", "사건을 6번에서 2006~2025년 전체로 늘려요."],
    done: [["시뮬레이션 채점", true], ["전체 사건 채점", false]],
    now: "시뮬레이션: 운영자 방류 증가 107번 중 46번을 먼저 알림(가운데 9.5시간 앞섬). 헛알림 166번 중 절반은 조정지(모델 문제).",
    links: [L.webAlert, L.scen] },
  { id: "T55", phase: "p5", status: "todo", title: "한계와 예외 정리",
    lead: "최종 채점 '한계·예외 고려' 항목을 발표 한 장으로.",
    why: "분석이 어디까지 믿을 만한지 스스로 밝히는 게 채점 기준이에요.",
    how: ["큰 홍수는 드물다 → 큰물 시간만 따로 채점, 사건 수를 같이 적어요.", "유입량은 잰 값이 아니라 계산값 → 처리 전후 비교.", "방류는 사람이 정한다 → 예측 대상이 아니라 입력·채점 기준으로만.", "ASOS는 당일 자료가 없다 → 실시간이 아니라 과거 분석용.", "같이 움직인다고 원인은 아니다 → '관계가 보인다'로 표현."],
    done: [["한계 슬라이드 한 장", false]] },

  // ───────────── 6. 웹 화면 ─────────────
  { id: "T60", phase: "p6", status: "doing", title: "방류 계산기",
    lead: "댐 운영자용. '넘치지 않으려면 지금 최소 몇 ㎥/s 내보내야 하나'를 답해요.",
    why: "최종 목표 ①이에요. 예측(T51)과 계산식을 운영자가 바로 쓸 수 있는 숫자로 바꿔요.",
    how: ["입력: 지금 수위·저수량, 3·6·12시간 뒤 예측 유입, 수위↔저수량 곡선, 계획홍수위.", "계산: 12시간 뒤 저수량 = 지금 + (들어올 물 − 내보낼 물) × 시간. 계획홍수위를 넘지 않는 가장 작은 일정 방류량을 찾아요.", "대상: 댐 36곳 + 조정지 6곳. 보·하굿둑은 제외(물을 흘려보내는 시설이라 기준 수위가 안 맞아요).", "최종에는 시제품 계산식을 그대로 두고 입력만 하둡 결과 표로 바꿔요."],
    done: [["시제품(로컬 데이터)", true], ["하둡 결과 표로 연결", false]],
    links: [L.webRelease, L.dash, L.common] },
  { id: "T61", phase: "p6", status: "doing", title: "재난 상황판",
    lead: "재난 담당자용. 모든 댐을 정상·경계·위험으로 나누고 위험한 댐이 위로 와요.",
    why: "최종 목표 ②예요. 같은 예측·계산을 지역 재난 대응에 맞게 보여 줘요.",
    how: ["12시간 뒤 예상 수위가 관리 기준 수위를 넘으면 경계, 계획홍수위를 넘으면 위험.", "과거 큰비 시점을 되감아 '그때 미리 알 수 있었나'를 보여 줘요.", "채점 함수 하나(common.js)를 웹과 보고서가 같이 써요."],
    done: [["시제품(로컬 데이터)", true], ["하둡 결과 표로 연결", false]],
    links: [L.webAlert, L.dash] },
  { id: "T62", phase: "p6", status: "decide", title: "웹이 데이터를 읽는 방법 정하기",
    lead: "MySQL+웹 서버로 할지, 정적 파일로 할지.",
    why: "과제 구조 그림에 'DB·웹 서버'가 구성요소로 들어가요. 정적 파일만 쓰면 그 부분이 빠져요.",
    how: ["A안(추천): Sqoop export → MySQL → 작은 웹 서버(Flask) → 화면. 과제 구조 그대로, VM에서 재현돼요.", "B안: Spark가 JSON으로 내보냄 → GitHub Pages. 링크 하나로 공유하기 쉬워요.", "둘 다: 최종 제출은 A, 팀 공유·발표 링크는 같은 결과를 JSON으로 뽑은 B."],
    done: [["방식 결정", false]] },

  // ───────────── 중간발표 ─────────────
  { id: "T70", phase: "m1", status: "todo", due: "2026-10-16", title: "중간 결과 만들기 (VM에서 샘플 돌리기)",
    lead: "가장 중요한 빈칸이에요. 샘플을 VM의 하둡에서 실제로 돌려 캡처해요.",
    why: "과제는 중간 결과를 '빅데이터 관리 시스템을 사용해서' 보여 달라고 해요. 지금까지 돌린 건 맥북 로컬 Spark라 하둡 결과라고 말할 수 없어요.",
    how: ["샘플: 이미 받은 원본 중 댐 6곳(소양강·안동·대청·용담·섬진강·남강) 2020~2026과 그 상류 관측소·근처 ASOS.", "HDFS에 올리고(T20) → Hive 원본 표(T21) → Spark 정제(T30) → Impala 조회(T41).", "캡처 목록: hdfs dfs -ls 결과, Hue 파일 화면, Hive DDL·COUNT, Spark 실행 로그(고친 개수), YARN 작업 성공 화면, Impala 결과와 걸린 시간, JSON vs Parquet 용량, 품질표.", "첫 예측 숫자 1개: 소양강 6시간 뒤, 기준선 오차 vs 모델 오차."],
    done: [["캡처 8장", false], ["첫 예측 숫자", false]],
    now: "VM(T02~T04)이 준비되면 바로 시작해요. 늦어도 10/16까지." },
  { id: "T71", phase: "m1", status: "todo", due: "2026-10-16", title: "중간발표 슬라이드 만들기 (약 10분)",
    lead: "과제가 정한 다섯 항목을 10장 안팎으로.",
    why: "중간 채점: 창의성, 실현 가능성, 완성도(예외), 계획, 발표.",
    how: ["아래 구성안대로 만들어요. 기존 팀 공유 덱(39장)에서 화면·차트를 가져와 줄여요."],
    table: { head: ["순서", "내용", "시간"], rows: [["1", "표지 · 팀 · 한 문장 목표", "0:30"], ["2", "문제: 비 → 강 → 댐, 몇 시간 뒤 물이 몰려오나(2023년 7월 소양강 실제 그래프)", "1:00"], ["3", "데이터셋 5종과 수집량", "1:00"], ["4", "최종 목표 2개: 방류 계산기 · 재난 상황판(시제품 화면)", "1:00"], ["5", "전체 구조 그림", "1:00"], ["6", "구성요소별 기능", "1:30"], ["7", "중간 결과: VM 캡처, 용량·속도 비교, 품질표", "1:30"], ["8", "분석 계획: 반응 시간 → 예측(관측소·ASOS 단계 실험) → 방류·경보", "1:00"], ["9", "예외 처리: 찾아낸 데이터 함정과 처리 규칙", "0:45"], ["10", "일정·역할", "0:45"]] },
    done: [["슬라이드 완성", false], ["팀 리허설 1번", false]] },
  { id: "T72", phase: "m1", status: "todo", due: "2026-10-18", title: "발표 영상 녹화",
    lead: "Zoom으로 화면 공유 + 발표자 전원 얼굴.",
    why: "과제 조건이에요: 발표하는 팀원 모두의 얼굴이 나와야 해요.",
    how: ["Zoom 회의에서 화면을 공유하고 발표자 모두 카메라를 켠 채 녹화해요.", "슬라이드별 발표자를 정하고 대본을 슬라이드 노트에 적어요.", "녹화 후 처음 30초를 다시 보며 얼굴·소리를 확인해요."],
    done: [["영상 파일 완성", false]] },
  { id: "T73", phase: "m1", status: "todo", due: "2026-10-19", title: "제출하고 팀원 평가하기",
    lead: "10/19 14:00까지 Google Drive에 세 가지를 올려요. 늦으면 받지 않아요.",
    why: "제출물: ① 녹화 영상 ② 슬라이드 ③ 보충 자료(소스코드 등).",
    how: ["e-class에 공지된 Google Drive 위치를 확인해요.", "영상, 슬라이드(PDF와 원본), 코드 압축 파일을 올려요.", "10/21 23:59까지 각자 e-class에서 팀원 평가를 해요."],
    done: [["세 가지 업로드", false], ["팀원 평가 완료(각자)", false]] },

  // ───────────── 최종발표 ─────────────
  { id: "T80", phase: "m2", status: "todo", due: "2026-12-06", title: "제출 패키지와 재현 매뉴얼",
    lead: "매뉴얼대로 하면 수업 VM에서 똑같이 돌아가야 해요.",
    why: "과제 원문: 소스코드 전체, 데이터 얻는 법, 배포 매뉴얼을 압축해 내고, 매뉴얼대로 표준 환경에서 재현돼야 해요.",
    how: ["소스코드: code/ 전체와 web/", "데이터 얻는 법: 인증키 발급 절차, 수집기 실행법, 걸리는 시간", "데이터 스냅샷: 키 없이도 재현할 수 있게 받아 둔 원본 일부(T14)", "매뉴얼: VM에서 적재 → Hive 표 → Spark 정제·분석 → Sqoop export → 웹 실행 순서"],
    done: [["압축 파일", false], ["팀원이 매뉴얼만 보고 VM에서 재현 성공", false]] },
  { id: "T81", phase: "m2", status: "doing", title: "문제 분석·디버깅 기록",
    lead: "겪은 문제를 '증상 → 원인 → 고친 방법 → 전후 숫자'로 모아요.",
    why: "최종 채점 항목이에요(문제 분석, 디버깅).",
    how: ["문제가 생길 때마다 아래 표에 한 줄씩 더해요."],
    table: { head: ["증상", "원인", "처리"], rows: [
      ["정상 응답인데 데이터 0바이트", "한 번에 받는 줄 수 한도 초과", "400·500·999줄로 나눠 받기"],
      ["관측소 자료가 해마다 1시간씩 빔", "API가 01~24시 표기, 끝 시각 23시로 조회", "끝 시각 24시 + 703개 파일 보충"],
      ["9시간 예측 정답이 엉뚱함", "Parquet 행 순서가 시간순 아님", "시각 기준으로 밀기 (0.50 → 0.87)"],
      ["방류 권고가 실제의 1.8배", "'12시간 안에 비우기'를 섞음", "최소 방류와 24시간 비우기 분리 (1.01배)"],
      ["경보 '정밀도 39%'가 부풀려짐", "이미 넘은 시간을 맞힌 것으로 셈", "운영자 방류 증가보다 먼저 알렸나로 채점"],
      ["저수량 13만 칸이 빈칸", "쉼표 숫자를 바로 숫자로 읽음", "원본 STRING, Spark에서 쉼표 제거"],
      ["관측소 호출 429 오류", "초당 한도", "호출 간격 0.3초"]] },
    done: [["최종 발표용 정리", false]], links: [L.dash, L.sim] },
  { id: "T82", phase: "m2", status: "todo", due: "2026-12-07", title: "최종 영상과 제출",
    lead: "약 15분. 구현 결과, 구성요소 상세, 디버깅 과정. 발표자 전원 얼굴.",
    why: "최종 제출물: 영상, 슬라이드, 보충 자료(압축 파일). 12/9 23:59까지 팀원 평가.",
    how: ["T72·T73과 같은 순서로 녹화·제출해요."],
    done: [["제출", false], ["팀원 평가(각자)", false]] },
];

// 자료실의 가이드. 할 일과 같은 화면 틀로 보인다.
export const GUIDES = [
  { id: "G1", title: "VM 가이드", lead: "수업 VM이 무엇인지, 왜 x86 PC가 필요한지, 팀원이 같이 보는 방법.",
    why: "과제 설명서는 최종 결과가 '표준 환경(예: the course practice VM)에서 재현'돼야 한다고 한 줄만 적었어요. 강의에도 VM 설치·버전·사양을 다룬 장은 없어요(1~5주차). 대신 실습 화면에 흔적이 있어요: CDH(Cloudera 배포판)를 실습에 쓰고 'Hue is used throughout this course'(1주차), /home/training 경로와 사용자 cloudera(2주차, 2013년 화면), loudacre MySQL 예제(3주차), 표 소유자 training·hdfs://localhost:8020(5주차, 2015년 화면). 즉 Cloudera 교육과정의 컴퓨터 한 대짜리 실습 이미지로 보여요. 정확한 버전은 자료에 없어요.",
    how: ["왜 맥북·맥미니는 안 되나: 이미지 안 운영체제가 x86용이에요. 애플 M 칩은 ARM이라 가상화 프로그램이 ARM 운영체제만 제 속도로 돌려요. VMware Fusion은 M 칩에서 x86 VM을 켜지 못하고, UTM은 흉내 내서 켜지만 몇 배~수십 배 느려 하둡에는 못 써요. Rosetta는 앱을 바꿔 주는 기능이라 VM 전체는 못 돌려요.",
      "윈도우만 되는 건 아니에요: 인텔·AMD(x86) PC면 돼요. 윈도우, 리눅스, 인텔 맥 모두 가능해요.",
      "팀원이 같이 보는 방법 ①(추천) Tailscale: 본 VM PC에 Tailscale을 깔고 VM 포트를 PC로 연결해요(Hue 8888, HDFS·YARN 화면, SSH 2222). 팀원은 Tailscale에 들어와 브라우저로 http://<PC 주소>:8888 에 접속해 표 조회·파일 보기·작업 확인을 하고, SSH로 hdfs·hive·spark-submit 명령도 써요.",
      "② 원격 데스크톱(크롬 원격 데스크톱·AnyDesk): 윈도우 화면을 넘겨받아요. 한 번에 한 명.",
      "③ Zoom 화면 공유: 회의 때 같이 보기.",
      "④ 결과 공유: 코드는 GitHub, 데이터는 공유 드라이브, 분석 결과는 이 허브."],
    table: { head: ["항목", "권장 (일반적인 한 대짜리 하둡 VM 기준, 확인 필요)"], rows: [["CPU", "인텔·AMD 4코어 이상, BIOS에서 가상화(VT-x / AMD-V) 켜기"], ["메모리", "16GB 이상 (VM에 8GB)"], ["저장공간", "SSD 여유 100GB 이상 (이미지 + 원본 약 15GB + 정리본)"], ["운영체제", "64비트 Windows 10/11 (또는 리눅스·인텔 맥)"], ["가상화 프로그램", "VirtualBox 또는 VMware Workstation. WSL2·Hyper-V가 켜져 있으면 VirtualBox가 느려질 수 있어요"]] },
    done: [["교수님 확인 후 권장 사양 확정", false]],
    traps: ["VM 포트를 공개 인터넷에 열지 마세요. 기본 계정·비밀번호가 알려져 있어요. Tailscale처럼 팀원만 들어오는 길로만.", "8GB VM 하나에서 여럿이 동시에 Spark를 돌리면 멈춰요. 무거운 작업은 순서를 정해요.", "본 VM PC는 작업 기간에 켜 두고 잠자기를 꺼요."],
    links: [{ label: "교수님께 VM 질문 보내기", sub: "0단계 준비의 할 일", href: "#/t/T03", kind: "할 일" }, { label: "VM을 돌릴 PC 정하기", sub: "0단계 준비의 할 일", href: "#/t/T02", kind: "할 일" }] },
  { id: "G2", title: "전체 구조", figure: "arch", lead: "데이터가 어디서 와서 어디로 가는지 한 장으로. 중간발표 슬라이드 ⑤의 초안이에요.",
    why: "과제는 '구성요소와 그 관계(화면·빅데이터 관리 시스템·DB·웹 서버)'를 그려 달라고 해요.",
    how: ["공공 API → 수집기(Python)가 원본 파일로 저장", "원본 → Flume(또는 hdfs dfs -put) → HDFS 원본 선반 → Hive 원본 표", "Spark 정제 → 정리 선반(Parquet·연도 파티션) → Impala로 조회·측정", "Spark 특징·분석 + Python 모델 → 결과 선반", "Sqoop export → MySQL → 웹 서버 → 방류 계산기 · 재난 상황판", "기준표(좌표·관측소 연결)는 MySQL에서 Sqoop import로 들어와요"] },
  { id: "G3", title: "다운로드한 뒤의 순서", lead: "원본은 고치지 않고 받고, 고치는 일은 하둡 안에서.",
    why: "단계마다 무엇을 확인해야 다음으로 넘어가는지 정해 두면, 중간에 데이터가 조용히 틀어지는 걸 막을 수 있어요.",
    table: { head: ["순서", "어디서", "하는 일", "확인할 것"], rows: [
      ["1", "맥미니", "빠진 것 다시 받기", "검사에서 빠진 파일 0"], ["2", "맥미니", "원본 압축 백업", "압축 전후 파일 수가 같음"],
      ["3", "맥미니 → 본 VM", "원본을 VM 공유 폴더로 옮기기", "VM 안에서 파일이 보임"], ["4", "본 VM", "HDFS 원본 선반에 올리기", "hdfs dfs -du 용량"],
      ["5", "본 VM", "Hive 원본 표(STRING)", "COUNT가 검사 행 수와 같음"], ["6", "본 VM", "Spark 정제 → Parquet", "고친 개수, 품질표"],
      ["7", "본 VM", "정리본 표 → Impala 조회", "용량·조회 시간 비교"], ["8", "본 VM", "기준표 Sqoop import", "표 행 수"],
      ["9", "본 VM", "Spark 학습표 → Python 모델 → 결과 표", "기준선 대비 개선률"], ["10", "본 VM", "Sqoop export → MySQL → 웹", "화면 숫자 = 결과 표"]] },
    how: ["원본 한 줄(값은 받은 그대로): {\"q_damcode\":\"1012110\",\"q_from\":\"2023-01-01\",\"q_to\":\"2023-12-31\",\"obsrdt\":\"01-01 24시 \",\"inflowqy\":54.583,\"rsvwtqy\":\"1,857.835\", …}",
      "Spark가 만든 정리본: damcode=1012110 | ts=2023-01-02 00:00 | inflow=54.583 | storage=1857.835 | year=2023",
      "중간발표 전에는 샘플로 3~7번을, 전체 수집이 끝나면 1~10번을 전체 데이터로 돌려요."] },
  { id: "G4", title: "API 5종 수집 명세", lead: "어떤 API를, 어떤 주소로, 몇 줄씩, 어떤 함정을 피해 받나.",
    why: "최종 제출물에 '데이터를 얻는 방법'이 들어가요. 이 표가 그 초안이에요.",
    table: { head: ["API", "주소", "한 번에", "범위", "함정"], rows: [
      ["수문 운영 정보 15099110", "B500001/dam/sluicePresentCondition/hourlist·delist", "400줄", "댐 59곳 × 2006~", "시각에 연도 없음, 24시 표기, 쉼표 숫자, 유입 0 이하"],
      ["댐코드 15099105", "B500001/dam/damCode/damCodelist", "—", "59곳", "하루 100번 한도"],
      ["우량수위 관측소 15099115", "…/excllncobsrvt/hourrf/hourrflist · hourwal/hourwallist", "500줄", "비 187 · 강 244곳 × 2006~", "01~24시 표기(끝 시각 24), 초당 한도, 시험용 관측소"],
      ["수문 제원 15099107", "B500001/dam/dataPresent/dataPresentlist", "—", "59곳", "좌표 없음, 쉼표 숫자"],
      ["기상청 ASOS 15057210", "1360000/AsosHourlyInfoService/getWthrDataList", "999줄", "전국 100곳 × 2006~", "전날까지만, 강수 빈칸=0·표시 9=결측"]] },
    how: ["예비 경로: K-water API가 막히면 WAMIS(키 없이)에서 같은 댐 시간 자료를 받을 수 있어요(댐 49곳).", "키 받는 법: data.go.kr 가입 → 위 5개 API 활용신청(자동 승인) → 마이페이지에서 일반 인증키(Decoding) 복사."] },
  { id: "G5", title: "10/10 팀 회의 안건 검토", lead: "회의에서 나온 4가지를 수업·과제 기준으로 다시 본 의견.",
    why: "수업을 듣기 전에 정한 것이라 과제 요구사항과 맞는지 한 번 더 확인했어요.",
    table: { head: ["안건", "회의 내용", "의견"], rows: [
      ["원본 저장 위치", "팀원 PC에 저장", "수집은 맥미니에서 하는 것으로 바뀌었어요. 과제의 '저장'은 HDFS에 넣는 것이라, 원본의 정본은 VM의 HDFS, 백업은 공유 드라이브에 둬요."],
      ["수집 기간", "약 5일", "키 3개로 3일(10/10 ~ 10/12)로 줄었어요."],
      ["전처리 위치", "VM 안/밖 미정", "VM 안 Spark를 추천해요. 밖에서 고치면 하둡이 보관함만 남아 '데이터 관리 깊이'가 약해지고 재현도 어려워요. 수집기는 형태만 맞춰요."],
      ["처리 프로그램", "Spark로 결정", "Spark를 주 엔진으로 쓰는 건 맞아요. 다만 Hive(표 정의·파티션)와 Impala(조회·효율 측정)를 붙여야 과제 구조(예시: Hive/Impala 표 → Spark 분석)를 채워요."]] } },
  { id: "G6", title: "우리가 만드는 것", lead: "비가 오면 몇 시간 뒤 댐에 물이 몰려오는지 미리 맞혀, 운영자와 재난 담당자에게 알려 줘요.",
    why: "팀 회의(10/10)에서 최종 목표를 두 개로 정했어요. 둘은 같은 유입량 예측을 공유해요.",
    how: ["① 방류 계산기(댐 운영자): 넘치지 않으려면 지금 최소 몇 ㎥/s 내보내야 하나.", "② 재난 상황판(재난 담당자): 어느 댐이 몇 시간 뒤 위험해지나.", "공통 엔진: 3·6·12시간 뒤 유입량 예측. 상류 관측소·기상청 날씨로 정확도를 올려요."],
    links: [{ label: "방류 계산기", sub: "6단계 웹 화면의 할 일", href: "#/t/T60", kind: "할 일" }, { label: "재난 상황판", sub: "6단계 웹 화면의 할 일", href: "#/t/T61", kind: "할 일" }, { label: "관측소·ASOS로 예측 정확도 올리기", sub: "5단계 분석의 할 일", href: "#/t/T52", kind: "할 일" }, L.webRelease, L.webAlert] },
];

// 과제 요구사항: 원문 → 쉬운 말 → 어디서 채우나
export const REQS = [
  { group: "중간발표 · 10/19 14:00 · 10%", items: [
    { en: "Choose data sets to analyze", ko: "분석할 데이터셋 고르기", status: "done", where: ["G4"] },
    { en: "Present how to collect, store, and analyze the data sets in a big data management system (i.e., Hadoop framework)", ko: "하둡에서 어떻게 모으고, 저장하고, 분석할지", status: "doing", where: ["G2", "G3"] },
    { en: "Present the expected results … for example, using Web-based applications", ko: "기대 결과를 웹 등으로 보여 주기", status: "done", where: ["T60", "T61"] },
    { en: "Design the overall architecture for big data management", ko: "전체 구조 설계", status: "doing", where: ["G2"] },
    { en: "Slide: Basic idea (data sets, final target)", ko: "슬라이드 ① 기본 아이디어", status: "todo", where: ["G6", "T71"] },
    { en: "Slide: System overview and architecture", ko: "슬라이드 ② 시스템 개요와 구조", status: "todo", where: ["G2", "T71"] },
    { en: "Slide: Detailed functionalities", ko: "슬라이드 ③ 구성요소별 기능", status: "todo", where: ["T71"] },
    { en: "Slide: Intermediate results (using big data management systems … sample data)", ko: "슬라이드 ④ 중간 결과 — 샘플을 하둡에서 돌린 것", status: "todo", where: ["T70"] },
    { en: "Slide: Project plan", ko: "슬라이드 ⑤ 프로젝트 계획", status: "todo", where: ["T71"] },
    { en: "Video ~10 min, faces of all presenting members, submit video + slides + materials to Google Drive", ko: "영상 약 10분(전원 얼굴) + 슬라이드 + 보충 자료 제출, 10/21 팀원 평가", status: "todo", where: ["T72", "T73"] },
    { en: "Evaluation: creativity · feasibility · completeness (exceptional cases) · planning · presentation", ko: "채점: 창의성 · 실현 가능성 · 완성도(예외) · 계획 · 발표", status: "doing", where: ["T31", "T81"] }] },
  { group: "최종발표 · 12/7 14:00 · 20%", items: [
    { en: "Use big data management systems such as HDFS, Sqoop, Impala, and Hive", ko: "HDFS·Sqoop·Impala·Hive로 수집·저장·처리", status: "todo", where: ["T20", "T22", "T40", "T41"] },
    { en: "Any analysis tool or programming languages (e.g., Python)", ko: "분석 도구는 자유(Python 가능)", status: "doing", where: ["T51", "T52"] },
    { en: "Depth of data management — efficiency and appropriateness of tools", ko: "데이터 관리의 깊이 — 도구 선택의 효율성·적절성", status: "todo", where: ["T41"] },
    { en: "Depth of analysis — methods, insights, limitations and exceptional cases", ko: "분석의 깊이 — 방법, 통찰, 한계·예외", status: "doing", where: ["T52", "T55"] },
    { en: "Analyzing the problems that occurred and debugging them", ko: "문제 분석과 디버깅 과정", status: "doing", where: ["T81"] },
    { en: "Source codes, how to obtain the data, manual — reproducible in the course practice VM", ko: "소스코드·데이터 얻는 법·매뉴얼, 수업 VM에서 재현", status: "todo", where: ["T80"] },
    { en: "Video ~15 min, faces of all presenting members", ko: "영상 약 15분(전원 얼굴), 12/9 팀원 평가", status: "todo", where: ["T82"] }] },
];

export const DOCS = [
  { title: "가이드", items: GUIDES.map((g) => ({ label: g.title, sub: g.lead, href: `#/t/${g.id}`, kind: "가이드" })) },
  { title: "보고서", items: [L.overview, L.sim, L.dash] },
  { title: "시제품 화면", items: [L.webRelease, L.webAlert, L.webIndex] },
  { title: "코드", items: [L.collector, L.verify, L.etl, L.analyze, L.scen, L.common] },
];

export const LOG = [
  ["09-25", "과제 설명서 받음"],
  ["10-05", "팀원 제안 WaterPulse로 주제 확정, API 5종 신청·승인·호출 확인"],
  ["10-05", "실데이터 사전 시뮬레이션(로컬): 수집 → 정제 → 분석, 웹 시제품 공개"],
  ["10-06", "방류 계산기·재난 상황판 추가, 리뷰 반영(9시간 예측 버그, 채점 기준 변경, 방류 권고 1.8배 → 1.01배)"],
  ["10-10", "최종 목표 확정(방류 계산기 + 재난 상황판), 프로젝트 허브 공개"],
  ["10-10", "원본 전체 수집 시작(맥미니, 키 3개), 관측소 24시 누락 발견·수정"],
];

// 예전 주소(#/r/ID, #s3 등)를 새 화면으로 잇는다.
export const ALIASES = {
  "R-1": "#/req", "R-2": "#/req", "R-3": "#/req", "R-4": "#/t/G2", "R-5": "#/req", "R-6": "#/t/G2", "R-7": "#/req", "R-8": "#/t/T70", "R-9": "#/req", "R-10": "#/req", "R-11": "#/t/T80",
  "G-1": "#/t/T60", "G-2": "#/t/T61", "G-3": "#/t/T51", "S-1": "#/t/T04", "S-2": "#/t/T01", "S-3": "#/t/T05", "S-4": "#/t/T10", "S-5": "#/t/G5",
  "C-0": "#/t/T10", "C-1": "#/t/G4", "C-2": "#/t/G4", "C-3": "#/t/G4", "C-4": "#/t/G4", "C-5": "#/t/G4", "C-6": "#/t/T13", "C-7": "#/t/G4", "C-8": "#/t/T70",
  "I-1": "#/t/T20", "I-2": "#/t/T23", "I-3": "#/t/T22", "P-1": "#/t/T30", "P-2": "#/t/T30", "P-3": "#/t/T30", "P-4": "#/t/T30", "P-5": "#/t/T30", "P-6": "#/t/T31",
  "H-1": "#/t/T21", "H-2": "#/t/T40", "H-3": "#/t/T41", "H-4": "#/t/T42", "A-1": "#/t/T50", "A-2": "#/t/T51", "A-3": "#/t/T52", "A-4": "#/t/T51", "A-5": "#/t/T53", "A-6": "#/t/T55",
  "W-1": "#/t/T60", "W-2": "#/t/T62", "W-3": "#/t/T60", "M-1": "#/t/T71", "M-2": "#/t/T70", "M-3": "#/t/T72", "M-4": "#/t/T73", "Z-1": "#/t/T80", "Z-2": "#/t/T81", "Z-3": "#/t/T82",
  "D-1": "#/docs", "D-2": "#/docs", "D-3": "#/docs", "D-4": "#/docs", "D-5": "#/docs",
  req: "#/req", goal: "#/t/G6", s0: "#/roadmap/p0", s1: "#/roadmap/p1", s2: "#/roadmap/p2", s3: "#/roadmap/p3", s4: "#/roadmap/p4", s5: "#/roadmap/p5", s6: "#/roadmap/p6", mid: "#/roadmap/m1", fin: "#/roadmap/m2", lib: "#/docs",
};
