// WaterPulse 프로젝트 허브의 내용. 화면(hub.js)은 이 파일만 읽는다.
// 상태: done = 끝남, doing = 진행 중, todo = 할 일, decide = 팀 결정 필요.
// 과제 원문은 과제 설명서 Project_rev4_updated(2026) 그대로 옮긴다.

export const UPDATED = "2026-10-10";
export const MIDTERM = "2026-10-19T14:00:00+09:00";
export const FINAL = "2026-12-07T14:00:00+09:00";

const GH = "https://github.com/keemlogan/waterpulse/blob/main/";
const L = {
  overview: { label: "WaterPulse 한눈에 보기 (23쪽)", href: "docs/overview.pdf", kind: "pdf" },
  sim: { label: "실데이터 사전 시뮬레이션 보고서 (18쪽)", href: "docs/simulation.pdf", kind: "pdf" },
  dash: { label: "방류 계산기·재난 상황판 제작 보고서 (22쪽)", href: "docs/dashboard.pdf", kind: "pdf" },
  webIndex: { label: "시제품 · 분석 결과 화면", href: "../", kind: "app" },
  webRelease: { label: "시제품 · 방류 계산기", href: "../release.html", kind: "app" },
  webAlert: { label: "시제품 · 재난 상황판", href: "../alert.html", kind: "app" },
  collect: { label: "수집기 collect.py", href: GH + "code/sim/collect.py", kind: "code" },
  flume: { label: "적재 흉내 flume_sim.py", href: GH + "code/sim/flume_sim.py", kind: "code" },
  etl: { label: "정제 etl_spark.py", href: GH + "code/sim/etl_spark.py", kind: "code" },
  analyze: { label: "분석 analyze.py", href: GH + "code/sim/analyze.py", kind: "code" },
  scen: { label: "큰비 되감기 scenarios.py", href: GH + "code/sim/scenarios.py", kind: "code" },
  common: { label: "방류·경보 계산 common.js", href: GH + "common.js", kind: "code" },
  probe: { label: "API 확인 wp_probe.py", href: GH + "code/api_check/wp_probe.py", kind: "code" },
  portal: { label: "공공데이터포털", href: "https://www.data.go.kr", kind: "ext" },
};

// 파이프라인 단계. 목록 화면의 왼쪽 레일과 "흐름 한눈에" 띠가 이 순서를 따른다.
export const GROUPS = [
  { id: "req", label: "과제 요구사항", note: "과제 설명서 문장을 그대로 옮기고, 각 문장을 어디서 채우는지 연결했습니다.", due: "2026-10-19" },
  { id: "goal", label: "최종 목표", note: "팀 회의 결정: ① 방류량 계산과 ② 재난 경고판을 모두 만든다. 둘은 같은 유입량 예측을 공유한다.", due: null },
  { id: "s0", step: 0, label: "준비", note: "실습 VM, 역할, 인증키, 저장소 규칙", due: "2026-10-12" },
  { id: "s1", step: 1, label: "수집", note: "공공 API → 수집기(Python) → 원본 파일. API 5종 + 예비 1종", due: "2026-10-14" },
  { id: "s2", step: 2, label: "적재", note: "원본 파일 → Flume(또는 hdfs dfs -put) → HDFS 원본 선반, 기준표는 MySQL → Sqoop", due: "2026-10-15" },
  { id: "s3", step: 3, label: "전처리", note: "원본은 그대로 두고 Spark가 고친다. 자료마다 고칠 것이 다르다.", due: "2026-10-15" },
  { id: "s4", step: 4, label: "저장·조회", note: "Hive 표(원본·정리본·결과), Parquet·파티션, Impala 조회, Sqoop export", due: "2026-10-16" },
  { id: "s5", step: 5, label: "분석", note: "반응 시간 → 유입량 예측(관측소·ASOS로 정확도 올리기) → 방류 계산·경보 채점", due: "2026-11-23" },
  { id: "s6", step: 6, label: "웹 대시보드", note: "방류 계산기 + 재난 상황판 + 근거 화면", due: "2026-11-30" },
  { id: "mid", label: "중간발표", note: "영상 약 10분 · 슬라이드 · 보충 자료를 Google Drive에 · 10%", due: "2026-10-19" },
  { id: "fin", label: "최종발표", note: "영상 약 15분 · 슬라이드 · 소스코드·매뉴얼 압축 파일 · 20%", due: "2026-12-07" },
  { id: "lib", label: "자료실·진행 기록", note: "지금까지 만든 문서, 시제품, 코드, 진행 이력", due: null },
];

// 흐름 한눈에: 단계별 도구와 수업 연결
export const FLOW = [
  { group: "s1", title: "수집", tools: "Python 수집기", course: "과제 예시 4: periodic collector script", out: "원본 JSON 파일" },
  { group: "s2", title: "적재", tools: "Flume · hdfs dfs -put · Sqoop import", course: "강의 02 HDFS · 03 Sqoop · Flume(예정)", out: "HDFS /etl/waterpulse/raw" },
  { group: "s3", title: "전처리", tools: "Spark (DataFrame·SQL)", course: "Spark(예정)", out: "정리본 Parquet" },
  { group: "s4", title: "저장·조회", tools: "Hive · Impala · Hue", course: "강의 05 Impala·Hive · 파일 형식·파티션(예정)", out: "Hive 표 3층" },
  { group: "s5", title: "분석", tools: "Spark + Python(scikit-learn)", course: "Spark(예정) · 과제가 Python 허용", out: "예측·방류·경보 결과 표" },
  { group: "s6", title: "웹", tools: "Sqoop export → MySQL → 웹", course: "강의 03 Sqoop export", out: "방류 계산기 · 재난 상황판" },
];

// 남은 일정(2026-10-10 기준으로 다시 짠 것)
export const SCHEDULE = [
  { from: "2026-10-10", to: "2026-10-12", label: "준비: VM 버전 확인, 역할 나누기, 인증키 발급", group: "s0" },
  { from: "2026-10-11", to: "2026-10-13", label: "샘플 세트 확정 + ASOS 샘플 수집 + 기준표 작성", group: "s1" },
  { from: "2026-10-13", to: "2026-10-15", label: "VM에 샘플 적재 → Hive 원본 표 → Spark 정제", group: "s2" },
  { from: "2026-10-15", to: "2026-10-16", label: "Impala 조회 · 용량/속도 비교 캡처 · 첫 예측 숫자", group: "s4" },
  { from: "2026-10-14", to: "2026-10-17", label: "중간발표 슬라이드 제작", group: "mid" },
  { from: "2026-10-17", to: "2026-10-18", label: "Zoom 녹화(전원 얼굴) · 편집", group: "mid" },
  { from: "2026-10-19", to: "2026-10-19", label: "14:00 제출 마감 (늦은 제출 불가)", group: "mid", milestone: true },
  { from: "2026-10-21", to: "2026-10-21", label: "23:59 팀원 평가 마감", group: "mid", milestone: true },
  { from: "2026-10-13", to: "2026-10-18", label: "전체 수집 백그라운드 실행(키 나누면 2~3일) — 제안", group: "s1" },
  { from: "2026-10-20", to: "2026-11-02", label: "전체 원본 HDFS 적재(Flume) · 실패분 다시 받기", group: "s2" },
  { from: "2026-10-27", to: "2026-11-06", label: "전체 정제 · Hive/Impala 표 · 파티션 · 품질표", group: "s3" },
  { from: "2026-11-03", to: "2026-11-16", label: "예측 모델 단계 실험(댐만 → +관측소 → +ASOS → 상한)", group: "s5" },
  { from: "2026-11-10", to: "2026-11-23", label: "방류 계산·경보 채점 검증, 한계 정리", group: "s5" },
  { from: "2026-11-17", to: "2026-11-30", label: "웹 연결(Sqoop export → MySQL → 웹)", group: "s6" },
  { from: "2026-11-30", to: "2026-12-06", label: "VM 재현 매뉴얼 · 데이터 스냅샷 · 최종 녹화", group: "fin" },
  { from: "2026-12-07", to: "2026-12-07", label: "14:00 최종 제출 마감", group: "fin", milestone: true },
  { from: "2026-12-09", to: "2026-12-09", label: "23:59 팀원 평가 마감", group: "fin", milestone: true },
];

export const ITEMS = [
  // ───────────── 과제 요구사항 ─────────────
  { id: "R-1", group: "req", status: "done", title: "분석할 데이터셋 고르기",
    quote: "Choose data sets to analyze",
    summary: "K-water 수문 운영 정보(댐 상태), 우량수위 관측소(상류의 비·강), 수문 제원(댐 크기), 댐코드, 기상청 ASOS(날씨) 5종. 10월 5일 모두 승인받고 실제 호출로 값이 오는 것을 확인했다.",
    next: ["1단계 수집"], links: [L.overview] },
  { id: "R-2", group: "req", status: "doing", title: "하둡에서 어떻게 모으고, 저장하고, 분석할지",
    quote: "Present how to collect, store, and analyze the data sets in a big data management system (i.e., Hadoop framework)",
    summary: "수집기 → Flume → HDFS → Hive(표)·Impala(조회)·Spark(계산) → Sqoop → MySQL → 웹. 방법은 이 허브 1~6단계에 다 적었다. 남은 일은 수업 실습 VM에서 샘플로 실제로 돌려 보는 것이다.",
    gap: "지금까지 돌린 것은 맥북의 PySpark(로컬)이다. 하둡(HDFS·Hive·Impala) 위에서 돌린 것은 아직 없다. 중간발표 전에 VM에서 샘플을 돌려야 한다.",
    links: [L.overview] },
  { id: "R-3", group: "req", status: "done", title: "기대 결과를 웹 등으로 보여 주기",
    quote: "Present the expected results, which will be demonstrated as you preferred way, for example, using Web-based applications. The details could be ignored during idea proposal.",
    summary: "방류 계산기와 재난 상황판 시제품이 이미 있다(2020~2025년 실데이터로 큰비 6번을 되감아 보는 화면). 중간발표에서는 '최종 화면은 이렇게 된다'로 보여 준다.",
    links: [L.webRelease, L.webAlert, L.dash] },
  { id: "R-4", group: "req", status: "doing", title: "빅데이터 관리 전체 구조 설계",
    quote: "Design the overall architecture for big data management",
    summary: "아래 구조 그림이 초안이다. 슬라이드에 옮길 때 각 상자에 '무엇이 들어가고 무엇이 나오는지'를 한 줄씩 붙인다.",
    figure: "arch" },
  { id: "R-5", group: "req", status: "doing", title: "슬라이드 ① 기본 아이디어 (데이터셋, 최종 목표)",
    quote: "Basic idea (data sets, final target)",
    summary: "한 문장: 비가 오면 몇 시간 뒤 댐에 물이 몰려오는지 미리 맞혀, 댐 운영자에게는 '얼마나 내보내야 하는지', 재난 담당자에게는 '어느 댐이 위험해지는지'를 알려 준다.",
    next: ["최종 목표 G-1·G-2"] },
  { id: "R-6", group: "req", status: "doing", title: "슬라이드 ② 시스템 개요와 구조",
    quote: "System overview and architecture (components for overall service and their relationships; components could be the user interfaces, big data management systems, databases, or Web servers)",
    summary: "화면(웹) · 빅데이터 관리(HDFS·Hive·Impala·Spark) · DB(MySQL) · 웹 서버 네 덩어리와 그 사이의 화살표(Flume, Sqoop import/export)를 그린다.",
    figure: "arch" },
  { id: "R-7", group: "req", status: "doing", title: "슬라이드 ③ 구성요소별 상세 기능",
    quote: "Detailed functionalities (details for each component)",
    summary: "1~6단계 카드의 '하는 일'을 한 장에 한 구성요소씩 옮긴다: 수집기, Flume, HDFS 선반 3칸, Hive 표, Spark 작업, Impala 조회, Sqoop, MySQL, 웹 화면 2개." },
  { id: "R-8", group: "req", status: "todo", title: "슬라이드 ④ 중간 결과 (샘플을 하둡에서 돌린 것)",
    quote: "Intermediate results (using big data management systems, which will be connected to the Web services in the final result; at this stage, use sample data or a small subset of the data, not the entire large-scale data)",
    summary: "가장 중요한 빈칸이다. 샘플을 VM의 HDFS에 올리고 Hive 표를 걸고 Impala로 조회한 화면, JSON→Parquet 용량 비교, 파티션 전후 조회 시간, 첫 예측 숫자 1개를 캡처한다.",
    gap: "로컬 시뮬레이션 숫자(원본 429MB → Parquet 47MB 등)는 참고용이다. VM에서 다시 재야 '하둡에서 돌린 결과'라고 말할 수 있다.",
    next: ["M-2 중간 결과 만들기"] },
  { id: "R-9", group: "req", status: "todo", title: "슬라이드 ⑤ 프로젝트 계획",
    quote: "Project plan (you can optionally use project management software, e.g., bitrix24, Scrum)",
    summary: "이 허브의 일정표와 단계별 할 일을 그대로 쓴다. 역할(0단계)이 정해지면 담당자를 붙인다." },
  { id: "R-10", group: "req", status: "todo", title: "중간 채점 기준에 대한 우리 답",
    quote: "Creativity / Feasibility / Completeness (Include all the possible cases? Consider exceptional cases?) / Planning / Presentation",
    summary: "창의성: 비 → 강 → 댐 흐름을 따라가고, 결과를 운영자용 방류량과 재난 경고로 바꾼다. 실현 가능성: 실데이터 694만 줄로 이미 한 바퀴 돌려 봤다. 완성도(예외): 실제 호출로 데이터 함정을 미리 찾아 처리 규칙을 정했다(3단계 표, 최종발표 Z-2). 계획: 이 허브의 일정.",
    links: [L.sim] },
  { id: "R-11", group: "req", status: "todo", title: "최종 제출물 조건 (미리 알고 가기)",
    quote: "A compressed file for the supplementary materials including all the source codes, how to obtain the data, and a manual document describing how to deploy the source codes and data. Based on this manual, the implemented services should be reproducible in a standard environment (e.g., the course practice VM).",
    summary: "그래서 처음부터 VM에서 돌아가는 코드로 만든다. 인증키는 사람마다 다르므로 '키 받는 법'과 '받아 둔 데이터 스냅샷'을 함께 낸다.",
    next: ["최종발표 Z-1"] },

  // ───────────── 최종 목표 ─────────────
  { id: "G-1", group: "goal", status: "doing", title: "① 방류 계산기 — 지금 얼마나 내보내야 하나",
    summary: "댐 운영자가 보는 화면. 앞으로 12시간 들어올 물(예측)과 지금 수위를 넣으면 '계획홍수위를 넘지 않으려면 최소 몇 ㎥/s를 내보내야 하는지'를 답한다. 보조로 '24시간 안에 관리 기준 수위로 내리려면'도 보여 준다.",
    specs: [["누가 쓰나", "댐 운영자"], ["입력", "지금 수위·저수량, 3·6·12시간 뒤 유입량 예측, 수위↔저수량 곡선, 계획홍수위·관리 기준 수위(수문 제원)"],
      ["계산", "물 수지: 12시간 뒤 저수량 = 지금 저수량 + (들어올 물 − 내보낼 물) × 시간. 계획홍수위를 넘지 않는 가장 작은 일정 방류량을 찾는다."],
      ["대상", "댐 36곳 + 조정지 6곳 = 42곳 (보 16곳·하굿둑 1곳은 물을 흘려보내는 시설이라 제원의 계획홍수위가 평소 수위와 맞지 않아 제외)"],
      ["다 됐다의 기준", "과거 큰비에서 '더 내보내라' 답이 실제 운영자 방류와 비슷한 크기인가(시제품: 184번 중 실제의 1.01배)"]],
    steps: ["시제품 계산식(common.js assess)을 그대로 두고, 입력만 하둡에서 만든 결과 표로 바꾼다.",
      "예측이 좋아지면(5단계 A-3) 계산기 답도 같이 좋아진다. 계산 엔진 자체 오차는 평균 7cm로 작다(실제 유입을 넣었을 때).",
      "남은 일: 수위↔저수량 곡선을 정리본에서 다시 만들고, 튀는 값(승촌보 66.4m 등) 거르기 규칙을 Spark로 옮기기."],
    links: [L.webRelease, L.dash, L.common] },
  { id: "G-2", group: "goal", status: "doing", title: "② 재난 상황판 — 어느 댐이 위험해지나",
    summary: "재난 담당자가 보는 화면. 모든 댐을 정상·경계·위험으로 나누고, 위험한 댐이 위로 오게 정렬한다. 큰비가 왔던 과거 시점을 되감아 '그때 미리 알 수 있었나'를 확인한다.",
    specs: [["누가 쓰나", "재난 담당자, 하류 지자체"], ["입력", "방류 계산기와 같은 예측·계산 결과"],
      ["판정", "12시간 뒤 예상 수위가 관리 기준 수위를 넘으면 경계, 계획홍수위를 넘으면 위험"],
      ["채점 방법", "운영자가 실제로 방류를 늘리기 전에 경계·위험을 먼저 켰는가(운영자가 개입하므로 '실제로 넘쳤나'로 채점하지 않는다)"],
      ["시제품 결과", "운영자 방류 증가 107번 중 46번을 먼저 알림, 가운데 값 9.5시간 앞섬. 위험만 보면 11번·2시간. 먼저 못 알린 61번은 예측이 낮게 나온 탓"]],
    steps: ["채점 함수(common.js scoreScenario) 하나를 웹과 보고서가 같이 쓴다. 최종에도 유지한다.",
      "큰비 사건을 6번에서 2006~2025년 전체로 늘린다(전체 수집 후).",
      "헛알림 166번의 절반(조정지 82번)은 모델 문제이므로 조정지 처리 규칙을 정한다."],
    links: [L.webAlert, L.dash, L.scen] },
  { id: "G-3", group: "goal", status: "doing", title: "공통 엔진 — 3·6·12시간 뒤 유입량 예측",
    summary: "두 화면이 같은 예측을 쓴다. 예측이 약하면 둘 다 약해진다. 시제품 진단: 예측은 '실패'가 아니라 '약함'이고, 물이 두 배 넘게 불 때 실제의 68%(3시간 뒤)~45%(12시간 뒤)로 낮게 나온다. 주원인은 앞으로 올 비를 모른다는 것(입력이 지난 비뿐).",
    steps: ["정확도 올리기 계획은 5단계 A-3에 있다: 댐 자료만 → +상류 관측소 → +ASOS 날씨 → 앞으로 올 비를 안다고 가정한 상한.",
      "채점은 항상 '3시간 뒤에도 지금 그대로'라고 찍는 기준선 대비 몇 % 줄었나(skill)와, 큰물 때만 따로 계산한 값을 같이 낸다."],
    next: ["A-2", "A-3"], links: [L.sim] },

  // ───────────── 0. 준비 ─────────────
  { id: "S-1", group: "s0", status: "todo", title: "수업 실습 VM 버전 확인", due: "2026-10-11",
    summary: "최종 결과는 실습 VM에서 재현돼야 한다. 버전에 따라 쓸 수 있는 문법이 다르므로 가장 먼저 확인한다.",
    steps: ["VM을 켜고 아래 명령 결과를 이 카드에 적는다.",
      "디스크 여유와 메모리도 적는다(샘플 원본 약 0.5GB, 전체 원본은 수 GB 예상)."],
    code: "hadoop version\nhive --version\nimpala-shell --version\nspark-submit --version   # 또는 pyspark --version\npython3 --version; python3 -c \"import pandas, sklearn; print(pandas.__version__, sklearn.__version__)\"\nmysql --version; sqoop version; flume-ng version\ndf -h; free -g",
    traps: ["Spark 버전이 낮으면 시뮬레이션 코드의 일부 문법(sequence + interval 등)을 바꿔야 할 수 있다.",
      "VM에 scikit-learn이 없으면 설치 방법을 매뉴얼에 적어야 한다."] },
  { id: "S-2", group: "s0", status: "decide", title: "역할 나누기", due: "2026-10-11",
    summary: "겹치지 않게 네 줄기로 나누는 안: ① 수집·Flume ② Hive·Impala·Sqoop·MySQL ③ Spark 정제·분석 ④ 웹·발표 자료. 인원이 3명이면 ①과 ②를 합친다.",
    steps: ["담당자가 정해지면 이 허브의 각 카드에 담당자를 적는다(data.js의 owner)."] },
  { id: "S-3", group: "s0", status: "todo", title: "팀원별 인증키 발급", due: "2026-10-12",
    summary: "공공데이터포털 인증키는 사람마다 다르다. 각자 같은 5개 API를 신청해 두면 수집을 나눠 돌릴 수 있고, 하루 한도(기능별 10,000번)도 사람 수만큼 늘어난다.",
    steps: ["data.go.kr 회원가입 → 아래 5개 API 각각 '활용신청' (개발계정, 자동승인).",
      "15099110 수문 운영 정보 · 15099105 댐코드 조회 · 15099115 우량수위 관측소 운영 정보 · 15099107 수문 제원 현황 · 15057210 기상청 지상(종관, ASOS) 시간자료",
      "마이페이지의 '일반 인증키(Decoding)'를 각자 컴퓨터의 .env에 DATA_GO_KR_KEY=… 로 저장. 저장소에 올리지 않는다."],
    traps: ["기업회원 계정이면 신청할 때마다 개인/프로젝트 선택창이 뜬다 → '개인 서비스키'를 고른다.",
      "신청 폼 제출 시 확인창이 뜬다. 자동화 도구로 신청하면 탭이 멈출 수 있으니 손으로 누른다."],
    links: [L.portal] },
  { id: "S-4", group: "s0", status: "todo", title: "저장소·폴더 규칙", due: "2026-10-12",
    summary: "코드는 GitHub 저장소 하나에 모은다. 데이터와 키는 올리지 않는다.",
    specs: [["code/collector", "수집기"], ["code/flume", "Flume 설정 파일"], ["code/hive", "Hive·Impala DDL과 조회문"], ["code/spark", "정제·특징·분석 작업"],
      ["code/sqoop", "import/export 명령"], ["web", "대시보드"], ["docs/manual.md", "재현 매뉴얼(최종 제출물)"], [".gitignore", ".env, data/, *.log, .omc/"]] },

  { id: "S-5", group: "s0", status: "decide", title: "10/10 팀 회의 안건 검토 (수업·과제 기준 의견)", due: "2026-10-12",
    summary: "회의에서 나온 4가지를 수업 내용과 과제 요구사항에 비춰 다시 본 것. 결론은 팀이 정하고, 정해지면 이 카드와 관련 카드를 고친다.",
    table: { head: ["안건", "회의 내용", "의견", "제안"],
      rows: [["원본 저장 위치", "형도 형님 PC에 저장", "수집용 컴퓨터로는 좋다(며칠 켜 둬야 함). 다만 과제가 말하는 '원본 저장'은 하둡(HDFS)에 넣는 것이고, 한 사람 PC에만 있으면 고장·공유가 위험하다", "수집 = 형도 형님 PC, 원본의 정본 = VM의 HDFS 원본 선반, 백업 = 압축본을 공유 드라이브에(최종 제출의 데이터 스냅샷과 같은 것)"],
        ["수집 기간", "하루 호출 한도 때문에 약 5일", "계산이 맞다(강 관측소 43,920번 ÷ 하루 10,000번). 한도는 사람(키)·기능별이라 팀원 키로 관측소를 나누면 2~3일로 준다. 중간발표는 이미 받은 샘플로 충분하다", "수집기를 다듬어 10/13부터 백그라운드로 돌린다. 중간발표 준비와 겹치지 않고, 끝나면 바로 전체 적재로 넘어간다"],
        ["전처리 위치", "VM 안 / 밖 미정", "VM 안(Spark)을 추천. 밖에서 pandas로 고치면 하둡은 '보관함'만 남아 최종 채점의 '데이터 관리 깊이'가 약해지고, 매뉴얼대로 VM에서 재현하기도 어려워진다", "수집기는 형태만 맞춤(페이지 나눠 받기, JSON Lines, 댐·기간 정보 붙이기). 값을 고치는 일은 전부 VM의 Spark. 모델 학습만 Python(과제 허용)"],
        ["처리 프로그램", "Spark / Hive / Impala 중 Spark로 결정", "Spark를 주 엔진으로 쓰는 것은 맞다. 하지만 셋은 고르는 관계가 아니라 역할이 다르다. 과제 예시도 'Hive/Impala 표에 파티션으로 저장 → Spark로 분석' 구조다", "Spark = 정제·특징·분석, Hive = 표 정의(원본·정리본·결과, 메타스토어), Impala = 빠른 조회·성능 측정·웹 조회 확인. Spark가 Hive 메타스토어에 표를 같이 쓰므로 추가 품은 적다"]] },
    specs: [["원본 크기 추정", "전체 원본 JSON 최대 약 8.4GB (댐 1시간 1.5GB · 관측소 2.7GB · ASOS 3.6GB · 10분 0.6GB). ASOS는 열이 많아 행당 약 500바이트로 가장 크다"],
      ["정리본 크기 추정", "Parquet 약 0.5GB 추정 (시뮬레이션에서 댐 자료 9분의 1, 관측소 20~35분의 1로 줄었다)"],
      ["VM에 필요한 여유", "원본 + 정리본 + 작업 공간으로 약 15GB. 실습 VM은 컴퓨터 1대짜리라 HDFS 복사본은 1벌(dfs.replication 확인)"],
      ["회의에서 빠진 것", "실습 VM 버전·사양(S-1, 모든 결정의 전제), 역할(S-2), 웹이 데이터를 읽는 방법(W-2), Flume·Sqoop을 쓰는 자리(I-2·I-3·H-4)"]],
    steps: ["Spark만 쓰면 생기는 빈칸: 강의 05(Impala·Hive 데이터 모델링)에서 다루는 표 설계·파티션·메타스토어가 발표에서 빠진다. 과제 예시 2·4는 'Hive/Impala tables partitioned by date'를 명시한다.",
      "Spark로 정하되 '표는 Hive에 등록, 조회와 속도 비교는 Impala'를 붙이면 회의 결론을 크게 바꾸지 않고 과제 구조를 채울 수 있다.",
      "VM이 약해서 전체 데이터 처리가 느리면: 각자 VM에서는 샘플로 개발하고, 전체 처리는 가장 사양이 좋은 PC의 VM에서 연도 파티션 단위로 한 번 돌린다.",
      "키를 나눠 받을 때는 각자 자기 키로 자기 몫(관측소 목록의 일부)을 받아 같은 파일 이름 규칙으로 공유 드라이브에 올리고, 수집 PC에서 합친다(파일 이름에 댐·관측소·연도가 있어 겹치지 않는다)."],
    traps: ["공공데이터포털 인증키는 개인 것이다. 남의 키를 한 PC에 모아 쓰기보다 각자 실행하는 편이 안전하다.",
      "Spark가 쓴 Parquet의 시각은 Impala에서 9시간 밀려 보일 수 있다(시간대 처리) → 정리본 표를 만든 뒤 같은 행을 Spark와 Impala로 한 번씩 조회해 맞춰 본다."] },

  // ───────────── 1. 수집 ─────────────
  { id: "C-0", group: "s1", status: "doing", title: "수집기 설계와 전체 수집량",
    summary: "수집기는 API를 불러 받은 그대로 파일로 저장만 한다. 고치는 일은 하둡 안에서 Spark가 한다(원본이 남아야 '하둡으로 처리했다'가 된다). 시뮬레이션 수집기(collect.py)를 VM용으로 다듬어 쓴다.",
    steps: ["작업 단위 = (자료 종류, 댐 또는 관측소, 기간). 파일 하나 = 댐×월(시간 자료) 또는 관측소×연(관측소·ASOS).",
      "페이지당 행 수를 지킨다: 댐 시간 자료 400 · 관측소 500 · ASOS 999. 넘기면 오류 없이 빈 답이 온다.",
      "빈 답·네트워크 오류는 0.5초·1초·2초 쉬고 3번까지 다시 요청, 그래도 안 되면 실패 목록에 남긴다.",
      "관측소 API는 초당 한도가 있다 → 동시에 3갈래까지, 호출 사이 0.3초.",
      "이미 받은 파일은 건너뛴다 → 끊겨도 다시 실행하면 이어 받는다.",
      "호출마다 logs/calls.jsonl에 한 줄(자료, 대상, 페이지, 걸린 시간, 행 수, 문제). 발표의 '수집 통계' 근거.",
      "다 받은 파일은 spool/ 폴더로 옮긴다 → Flume이 거기서 HDFS로 가져간다(2단계)."],
    table: { head: ["자료", "범위", "호출 수", "걸리는 날", "최대 행 수"],
      rows: [["댐 시간 자료", "댐 59곳 × 2006~2026", "27,258", "3일", "1,085만"],
        ["비 관측소 시간 자료", "187곳 × 2016~2025", "33,660", "4일", "3,776만 (비+강 합)"],
        ["강 관측소 시간 자료", "244곳 × 2016~2025", "43,920", "5일", ""],
        ["ASOS 시간 자료", "약 40곳 × 2006~2025", "약 7,040", "1일", "약 701만"],
        ["댐 10분 자료 (선택)", "댐 15곳 × 5년", "9,900", "1일", "394만"],
        ["댐 일 자료·제원·댐코드", "59곳 전체 기간", "약 1,200", "1일 미만", "약 40만"]] },
    note: "하루 한도는 기능별 10,000번이라 종류가 다르면 동시에 받을 수 있다. 가장 오래 걸리는 강 관측소 기준 약 5일. 팀원 키를 나눠 쓰면 더 줄어든다. ASOS 호출 수는 999행씩 받는 기준으로 이번에 다시 계산했다.",
    links: [L.collect, L.overview] },
  { id: "C-1", group: "s1", status: "done", title: "댐코드 조회 (15099105)",
    summary: "댐·보 59곳의 이름과 번호. 다른 API를 부를 때 주소로 쓴다.",
    specs: [["경로", "apis.data.go.kr/B500001/dam/damCode/damCodelist"], ["인자", "serviceKey, _type=json"], ["양", "59행, 1번 호출"], ["한도", "하루 100번 (충분)"], ["저장", "raw/meta/damcode.json → 기준표 dam(댐코드·이름·종류)"]],
    traps: ["댐 종류(댐·보·조정지·하굿둑)는 이 API에 없다. 수문 제원 자료와 이름으로 붙인다."] },
  { id: "C-2", group: "s1", status: "done", title: "수문 제원 현황 (15099107)",
    summary: "댐의 신체검사표: 높이, 유역 넓이, 총 저수용량, 계획홍수위, 관리 기준 수위, 저수위. 방류 계산과 경보 판정의 기준선이 여기서 나온다.",
    specs: [["경로", "apis.data.go.kr/B500001/dam/dataPresent/dataPresentlist"], ["양", "59행"], ["쓰는 곳", "G-1 계획홍수위·관리 기준 수위, A-1 유역 넓이와 반응 시간 비교"]],
    traps: ["좌표(위도·경도)가 없다 → C-6 기준표를 직접 만든다.",
      "숫자가 '1,490'처럼 쉼표 문자열로 온다.",
      "일부 댐은 관리 기준 수위가 0이거나 저수위보다 낮다(군남·평화의댐 등) → 판정에서 무시하는 규칙."] },
  { id: "C-3", group: "s1", status: "done", title: "수문 운영 정보 (15099110) — 주인공",
    summary: "댐의 상태: 수위, 강우량(댐 지점), 유입량, 총 방류량, 저수량, 저수율. 예측의 정답(유입량)과 방류 계산의 출발점(수위·저수량)이 모두 여기 있다.",
    specs: [["경로", "…/dam/sluicePresentCondition/hourlist (시간) · delist (일) · mntlist (10분)"], ["인자", "damcode, stdt, eddt (YYYYMMDD), numOfRows, pageNo"],
      ["페이지 한도", "시간 자료 490행까지, 10분 자료 432행까지 → 400으로 고정"], ["기간", "2006년부터, 조회 기간 제한 없음"],
      ["수집 목표", "중간: 시뮬레이션에서 받은 2020~2025 시간 자료(59곳, 310만 행) 재사용 · 최종: 2006~2026 전체"],
      ["파일", "spool/dam_hourly/{damcode}_{YYYY-MM}.json"]],
    traps: ["시각에 연도가 없다: \"07-14 01시\" → 조회 기간에서 연도를 붙인다(3단계).",
      "하루의 끝이 \"24시\" → 다음 날 00시로.",
      "유입량은 저수량 변화로 계산한 값이라 0 이하가 섞인다(시뮬레이션 2020~2025: 40만 시간).",
      "불가능한 유입량 17개(광동 4,223만 ㎥/s 등)."],
    links: [L.probe, L.collect] },
  { id: "C-4", group: "s1", status: "doing", title: "우량수위 관측소 운영 정보 (15099115) — 상류의 비와 강",
    summary: "댐 번호를 넣으면 그 댐 상류의 비 관측소와 강 관측소를 알려 주고, 관측소별 시간 강우·강 수위·유량을 준다. 비가 댐에 닿기 전에 '강에서 먼저 불어나는 것'을 볼 수 있어 예측 정확도를 올리는 핵심 자료다.",
    specs: [["관측소 목록", "…/dam/excllncobsrvt/excll/exclllist (비) · wal/wallist (강), 인자 damcode"],
      ["시간 자료", "…/hourrf/hourrflist (시간 강우) · hourwal/hourwallist (시간 수위·유량), 인자 damcode, obscd, stdt, eddt"],
      ["페이지 한도", "500행 (999행은 일부 쪽이 빈 답)"], ["관측소 수", "비 187곳 · 강 244곳 (댐마다 0~21곳, 예: 소양강 비 13·강 9, 대청 비 17·강 11)"],
      ["수집 목표", "중간: 샘플 댐 3곳(소양강·안동·대청)은 시뮬레이션에서 이미 받음(비 39곳·강 28곳, 2020~2025) · 최종: 431곳 × 2016~2025"],
      ["파일", "spool/rain_hourly/{damcode}_{obscd}_{YYYY}.json, spool/level_hourly/…"]],
    traps: ["초당 한도 초과(HTTP 429, 코드 23) → 3갈래 + 0.3초 간격.",
      "관측소 목록에 시험용 지점('시험2')이 섞여 있다 → 뺀다.",
      "영주·성덕·보현산 댐은 상류 관측소가 0곳 → ASOS로 메운다(C-5).",
      "한 관측소가 여러 댐의 상류에 동시에 속할 수 있다 → 연결표(C-6)를 댐-관측소 다대다로 둔다."],
    links: [L.collect] },
  { id: "C-5", group: "s1", status: "todo", title: "기상청 ASOS 시간자료 (15057210) — 날씨 더하기", due: "2026-10-13",
    summary: "기상청 유인 관측소의 시간별 강수량·기온·습도·기압·풍속·적설. 관측소 API가 비어 있는 곳의 비를 메우고, 땅이 젖은 정도(최근 며칠 비)·눈 녹는 계절(기온)처럼 K-water 자료에 없는 정보를 더한다.",
    specs: [["경로", "apis.data.go.kr/1360000/AsosHourlyInfoService/getWthrDataList"],
      ["인자", "dataCd=ASOS, dateCd=HR, startDt·startHh, endDt·endHh, stnIds, numOfRows, pageNo, dataType=JSON"],
      ["페이지 한도", "999행 (1000행부터 거부, 10/10 확인). 1년 범위를 한 번에 조회 가능(8,760행 → 9쪽)"],
      ["제공 범위", "어제까지 ('전날 자료까지 제공됩니다' 오류)"],
      ["쓸 열", "rn 강수량, ta 기온, hm 습도, pa 기압, ws 풍속, dsnw 적설, 각 Qcflg 품질 표시"],
      ["확인한 지점 번호", "춘천 101 · 인제 211 · 안동 136 · 영주 272 · 문경 273 · 청주 131 · 대전 133 · 보은 226 · 금산 238 · 장수 248 · 임실 244 · 산청 289 · 진주 192 · 영덕 277"],
      ["수집 목표", "중간: 샘플 댐 3곳 근처 6곳(101·211·136·131·133·226) × 2020~2025 = 약 320번 · 최종: 판정 대상 42곳(댐·조정지) 근처 약 40곳 × 2006~2025"],
      ["파일", "spool/asos_hourly/{stnId}_{YYYY}.json"]],
    steps: ["기상청 기상자료개방포털의 지점 정보에서 ASOS 지점 좌표를 받는다.",
      "댐마다 유역 안 또는 가장 가까운 ASOS 1~3곳을 고른다 → C-6 연결표 asos_dam.",
      "수집기에 asos_hourly 작업을 추가(연 단위 범위, 999행 페이징)."],
    traps: ["rn이 빈칸이고 품질 표시도 빈칸이면 비가 안 온 시간(0mm), rnQcflg가 9이면 결측. 10/10 호출에서 이 모양을 확인했다. 전처리 전에 같은 날 일자료 합계와 맞춰 규칙을 확정한다.",
      "ASOS는 도시·평지에 많고 댐 상류 산지에는 적다 → '댐에서 몇 km' 거리를 연결표에 같이 적어 해석에 쓴다.",
      "당일 자료는 없다 → 실시간 화면에는 쓸 수 없고 과거 분석·학습에만 쓴다."] },
  { id: "C-6", group: "s1", status: "todo", title: "기준표 만들기: 좌표·관측소 연결·ASOS 연결 (MySQL)", due: "2026-10-13",
    summary: "API로 받지 못하는 정보를 작은 표로 직접 만든다. 일반 DB(MySQL)에 두고 Sqoop으로 하둡에 가져온다 — 수업의 Sqoop import를 자연스럽게 쓰는 자리다.",
    table: { head: ["표", "열", "출처"],
      rows: [["dam", "damcode, name, kind, lat, lon, basin_km2, plan_flood_m, limit_m, low_m", "댐코드·제원 API + 좌표는 공개 자료로 직접 입력"],
        ["station_dam", "damcode, obscd, type(비/강), name, is_test", "관측소 목록 API(15099115)"],
        ["asos_dam", "damcode, stn_id, distance_km, in_basin", "ASOS 지점 좌표 + 댐 좌표로 계산"],
        ["level_curve", "damcode, storage, level", "시간 자료에서 수위·저수량 쌍으로 만든다(시제품과 같은 방법)"]] },
    steps: ["MySQL에 waterpulse_ref 데이터베이스와 표 4개를 만든다(DDL은 code/sqoop/ref.sql).",
      "CSV로 채운 뒤 LOAD DATA로 넣는다.",
      "2단계 I-3에서 Sqoop import로 Hive에 가져간다."] },
  { id: "C-7", group: "s1", status: "done", title: "예비 경로: WAMIS (키 없이)",
    summary: "K-water API가 막히면 국가수자원관리종합정보시스템(WAMIS)에서 같은 댐 시간 자료를 받는다. 소양강댐 값이 K-water와 같았다(댐 49곳).",
    code: "http://www.wamis.go.kr:8080/wamis/openapi/wkd/mn_hrdata?damcd=1012110&startdt=20230701&enddt=20230731&output=json" },
  { id: "C-8", group: "s1", status: "todo", title: "중간발표용 샘플 세트 확정", due: "2026-10-12",
    summary: "중간발표는 '전체가 아닌 샘플'이면 된다. 새로 다 받지 않고, 시뮬레이션에서 이미 받은 원본을 재사용하고 ASOS만 추가로 받는다.",
    table: { head: ["자료", "샘플 범위", "상태"],
      rows: [["댐 시간 자료", "59곳 × 2020~2025 (310만 행, 원본 429MB)", "받아 둠"],
        ["비·강 관측소", "소양강·안동·대청 상류 비 39곳·강 28곳 × 2020~2025 (345만 행)", "받아 둠"],
        ["댐 일 자료·제원·댐코드", "59곳", "받아 둠"],
        ["ASOS", "6곳 × 2020~2025 (약 32만 행)", "받을 것 · 약 320번 호출"]] },
    note: "VM 용량이 작으면 댐 시간 자료를 샘플 댐 6곳(소양강·안동·대청·용담·섬진강·남강)으로 줄인다." },

  // ───────────── 2. 적재 ─────────────
  { id: "I-1", group: "s2", status: "todo", title: "HDFS 폴더 설계 (선반 3칸)",
    summary: "수업 폴더 규칙대로 작업 중인 것은 /etl, 완성본은 /data에 둔다. 원본 → 정리본 → 결과 순서로만 흐른다.",
    code: "/etl/waterpulse/raw/{dam_hourly,dam_daily,rain_hourly,level_hourly,asos_hourly,meta}/   ← 받은 그대로 JSON\n/data/waterpulse/clean/{dam_hourly,rain_hourly,level_hourly,asos_hourly}/year=YYYY/   ← Parquet\n/data/waterpulse/ref/{dam,station_dam,asos_dam,level_curve}/   ← Sqoop import\n/data/waterpulse/mart/{features_hourly,forecast,release,alert,lag_events,quality}/   ← 분석 결과",
    traps: ["작은 파일 문제: HDFS는 '적당한 수의 큰 파일'에 맞다(강의 02). 댐×하루로 받으면 댐 자료만 약 45만 개 → 댐×월로 묶고, 정리본은 Spark가 큰 Parquet 파일로 합친다."] },
  { id: "I-2", group: "s2", status: "todo", title: "Flume으로 원본을 HDFS에 흘려보내기",
    summary: "수집기가 spool 폴더에 파일을 떨구면, Flume의 spooldir 소스가 그것을 읽어 HDFS 원본 선반으로 옮긴다. Flume을 배우기 전(중간발표)에는 hdfs dfs -put으로 같은 자리에 올린다.",
    code: "# 중간발표: 손으로 올리기\nhdfs dfs -mkdir -p /etl/waterpulse/raw/dam_hourly\nhdfs dfs -put spool/dam_hourly/*.json /etl/waterpulse/raw/dam_hourly/\n\n# 최종: code/flume/waterpulse.conf (자료 종류마다 소스 1개)\na1.sources = dam\na1.channels = c1\na1.sinks = k1\na1.sources.dam.type = spooldir\na1.sources.dam.spoolDir = /home/cloudera/waterpulse/spool/dam_hourly\na1.sources.dam.deserializer = org.apache.flume.sink.solr.morphline.BlobDeserializer$Builder\na1.channels.c1.type = file\na1.sinks.k1.type = hdfs\na1.sinks.k1.hdfs.path = /etl/waterpulse/raw/dam_hourly\na1.sinks.k1.hdfs.fileType = DataStream\na1.sinks.k1.hdfs.rollInterval = 0\na1.sinks.k1.hdfs.rollCount = 0\na1.sinks.k1.hdfs.rollSize = 134217728\na1.sources.dam.channels = c1\na1.sinks.k1.channel = c1",
    steps: ["시뮬레이션의 flume_sim.py가 같은 동작(폴더 감시 → 옮기기 → .COMPLETED 표시)을 흉내 낸 것이다.",
      "Flume 강의 후 설정 파일 세부(파일 단위로 보낼지, 줄 단위로 보낼지)를 확정한다. 위 설정은 초안이다.",
      "rollSize를 HDFS 블록 크기(128MB)에 맞춰 작은 파일을 줄인다."],
    traps: ["spool 폴더에 쓰는 중인 파일을 Flume이 읽으면 오류 → 수집기는 임시 이름으로 쓰고 다 쓴 뒤 이름을 바꾼다.",
      "Flume이 원본 파일명을 잃으면 연도·댐 정보가 사라진다 → JSON 안에 damcode·조회 기간을 함께 저장해 둔다."],
    links: [L.flume] },
  { id: "I-3", group: "s2", status: "todo", title: "Sqoop import: 기준표 MySQL → Hive",
    summary: "C-6에서 만든 기준표 4개를 하둡으로 가져온다. 작은 표라 매퍼 1개면 충분하다.",
    code: "sqoop import \\\n  --connect jdbc:mysql://localhost/waterpulse_ref \\\n  --username <VM 계정> -P \\\n  --table station_dam \\\n  --target-dir /data/waterpulse/ref/station_dam \\\n  --hive-import --hive-table wp.ref_station_dam \\\n  -m 1",
    traps: ["Hive 표 이름이 이미 있으면 덮어쓸지(--hive-overwrite) 정해 둔다.", "VM의 MySQL 계정·비밀번호는 매뉴얼에 적되 저장소에는 올리지 않는다."] },

  // ───────────── 3. 전처리 ─────────────
  { id: "P-1", group: "s3", status: "done", title: "전처리 원칙",
    summary: "원본 선반은 절대 고치지 않는다. 원본 Hive 표는 모든 열을 글자(STRING)로 걸고, 숫자·날짜 변환은 Spark가 정리본을 새로 쓰면서 한다. 고친 규칙과 고친 개수는 품질표(P-6)에 남긴다.",
    steps: ["왜 STRING인가: Hive는 읽을 때 형식을 확인한다(schema on read, 강의 05). \"1,946.781\" 같은 값은 숫자 열에서 조용히 NULL이 된다. 시뮬레이션에서 그냥 변환하면 저수량 13만 칸이 사라졌다.",
      "Spark 설정: spark.sql.ansi.enabled=false(Spark 4 기본값이 달라 Hive처럼 NULL로 두려면 필요), spark.sql.warehouse.dir를 임시 폴더로(한글·띄어쓰기 경로 문제)."],
    links: [L.etl] },
  { id: "P-2", group: "s3", status: "done", title: "댐 시간 자료 전처리 규칙",
    table: { head: ["원본 모양", "문제", "처리", "시뮬레이션에서 고친 수"],
      rows: [["obsrdt \"07-14 01시\"", "연도 없음", "파일의 조회 기간에서 연도를 붙인다", "310만 행 전체"],
        ["\"07-14 24시\"", "24시 표기", "다음 날 00시로", "129,327"],
        ["\"1,946.781\"", "쉼표 문자열, 숫자와 섞임", "쉼표 제거 후 double", "저수량 131,738 등"],
        ["inflowqy ≤ 0", "계산값이라 음수·0", "inflow_le0 표시 열 + 학습 대상은 지난 3시간 양수 평균", "401,906"],
        ["4,223만 ㎥/s 등", "불가능한 값", "댐 상위 0.1% 값의 10배 이상이면서 앞뒤 시간의 10배 이상 → NULL", "17"],
        ["수위·저수량 튐", "승촌보 66.4m 등", "같은 규칙으로 NULL", "수위 257 · 저수량 515"],
        ["빈 시간", "자료가 없는 시간", "댐별 시작~끝 1시간 격자를 만들어 빈칸을 드러낸다(비가 안 온 것과 구분)", ""]] },
    traps: ["Spark가 쓴 Parquet은 댐 안에서도 시간순이 아니다. 'N행 뒤'로 밀지 말고 '시각+N시간'으로 찾아야 한다(9시간 예측 정답이 이것 때문에 틀렸었다: 합 기준 0.50 → 고친 뒤 0.87)."] },
  { id: "P-3", group: "s3", status: "done", title: "관측소 자료 전처리 규칙",
    table: { head: ["문제", "처리"],
      rows: [["시각 형식이 댐 자료와 같다(연도 없음·24시)", "P-2와 같은 함수 재사용"],
        ["시험용 관측소", "station_dam.is_test로 제외"],
        ["관측소 고장·빈칸", "관측소×월 빈칸 비율을 품질표에, 빈칸 30% 넘는 달은 평균에서 제외"],
        ["관측소마다 해발·위치가 다름", "비는 댐별 상류 관측소 평균(유역 평균 강우의 근사), 강은 수위 변화량(1·3시간)과 유량 합으로 바꿔 댐 단위로 모은다"],
        ["한 관측소가 여러 댐에 속함", "연결표로 댐마다 복사해 붙인다(다대다)"]] } },
  { id: "P-4", group: "s3", status: "todo", title: "ASOS 자료 전처리 규칙",
    table: { head: ["문제", "처리"],
      rows: [["rn 빈칸", "rnQcflg 빈칸이면 0mm, 9이면 결측(일자료 합계로 확인 후 확정)"],
        ["tm \"2023-07-01 05:00\"", "연도 있음, 그대로 timestamp. K-water 자료와 같은 한국 시간인지 한 번 확인"],
        ["숫자가 문자열", "double로 변환, 빈칸은 NULL"],
        ["지점이 댐에서 멀다", "asos_dam.distance_km로 가중 평균(가까울수록 크게) 또는 가장 가까운 1곳"],
        ["적설 dsnw", "겨울·봄 눈 녹는 시기 특징으로만 사용"]] } },
  { id: "P-5", group: "s3", status: "todo", title: "통합 학습표 (features_hourly)",
    summary: "한 줄 = 한 댐의 한 시각. 댐 자료 + 상류 관측소 + ASOS를 시각으로 붙이고, 시간을 앞뒤로 밀어 '지난 몇 시간'과 '몇 시간 뒤(정답)' 열을 만든다. Spark Window 함수로 만든다.",
    table: { head: ["묶음", "열", "출처"],
      rows: [["댐", "지난 3시간 평균 유입 s3, 1·2·3·6·12시간 전 s3, 변화량, 댐 지점 3·6·12·24시간 강우 합, 저수율, 방류량", "C-3"],
        ["상류 관측소", "상류 평균 강우(1·3·6·12·24시간 합), 강 수위 변화(1·3시간), 강 유량 합과 3시간 변화", "C-4"],
        ["ASOS", "ASOS 강우 3·6·12·24시간 합, 최근 3·7·30일 강우(땅이 젖은 정도), 기온, 습도, 적설", "C-5"],
        ["달력", "월, 시", ""],
        ["정답", "3·6·12시간 뒤 s3", "C-3"]] },
    links: [L.analyze] },
  { id: "P-6", group: "s3", status: "doing", title: "데이터 품질표",
    summary: "'예외를 이미 보고 있다'는 증거. 댐·관측소별 기간, 빈칸 비율, 0 이하 유입량 비율, 고친 개수를 한 표로. 중간발표에 한 장 넣는다.",
    note: "시뮬레이션 예: 소양강 52,608시간 중 빈칸 0%, 0 이하 유입 29.8%. 남강 0 이하 12.0%.",
    links: [L.sim] },

  // ───────────── 4. 저장·조회 ─────────────
  { id: "H-1", group: "s4", status: "todo", title: "Hive 원본 표 (EXTERNAL, 전부 STRING)",
    summary: "원본 폴더에 표 이름표만 붙인다. EXTERNAL이라 표를 지워도 원본 파일은 남는다.",
    code: "CREATE DATABASE IF NOT EXISTS wp;\nADD JAR /usr/lib/hive-hcatalog/share/hcatalog/hive-hcatalog-core.jar;\nCREATE EXTERNAL TABLE wp.raw_dam_hourly (\n  obsrdt STRING, inflowqy STRING, totdcwtrqy STRING, rsvwtqy STRING,\n  rsvwtrt STRING, lowlevel STRING, rf STRING, damcode STRING, stdt STRING)\nROW FORMAT SERDE 'org.apache.hive.hcatalog.data.JsonSerDe'\nLOCATION '/etl/waterpulse/raw/dam_hourly';",
    traps: ["API 응답은 response.body.items.item 안에 배열로 들어 있다. 수집기가 item 배열만 한 줄에 한 건씩(JSON Lines) 저장하면 Hive JSON SerDe로 바로 읽힌다 → 수집기 저장 형식을 이렇게 정한다.",
      "JsonSerDe jar 경로는 VM 버전마다 다르다(S-1에서 확인)."] },
  { id: "H-2", group: "s4", status: "todo", title: "정리본 표 (Parquet, 연도 파티션)",
    summary: "Spark가 쓴 정리본 Parquet 폴더에 Hive 표를 건다. 파티션은 연도(필요하면 연·월)로. 댐×날짜처럼 잘게 나누면 작은 파일 문제가 다시 생긴다.",
    code: "CREATE EXTERNAL TABLE wp.dam_hourly (\n  damcode STRING, ts TIMESTAMP, inflow DOUBLE, outflow DOUBLE, storage DOUBLE,\n  storage_pct DOUBLE, level_m DOUBLE, rain_mm DOUBLE, inflow_le0 BOOLEAN)\nPARTITIONED BY (year INT)\nSTORED AS PARQUET\nLOCATION '/data/waterpulse/clean/dam_hourly';\nMSCK REPAIR TABLE wp.dam_hourly;   -- 폴더의 파티션을 표에 등록",
    traps: ["Parquet의 timestamp는 UTC로 저장되어 다른 도구에서 9시간 밀려 보일 수 있다(시뮬레이션에서 pandas가 겪음) → 한국 시간 변환 규칙을 한 곳에 둔다."] },
  { id: "H-3", group: "s4", status: "todo", title: "Impala 조회와 '관리 효율' 측정",
    summary: "과제는 관리 도구 선택의 '효율성과 적절성'을 본다. 같은 질문을 형식·파티션만 바꿔 재서 숫자로 보여 준다.",
    code: "INVALIDATE METADATA wp.dam_hourly;   -- 새 표\nREFRESH wp.dam_hourly;               -- 새 데이터\n\n-- 측정 질문: 2023년 7월 소양강 시간별 유입량\nSELECT ts, inflow FROM wp.dam_hourly\nWHERE year = 2023 AND damcode = '1012110' AND month(ts) = 7;\n-- 비교: raw(JSON, 파티션 없음) vs clean(Parquet, 파티션) 각각 3번 재서 가운데 값",
    table: { head: ["비교", "재는 것", "로컬 시뮬레이션 참고값"],
      rows: [["JSON → Parquet", "용량", "댐 시간 자료 429MB(354파일) → 47MB(73파일)"],
        ["파티션 없음 → 연도 파티션", "조회 시간, 읽은 바이트", "VM에서 측정"],
        ["Hive vs Impala", "같은 질문의 응답 시간", "VM에서 측정"]] } },
  { id: "H-4", group: "s4", status: "todo", title: "결과 표(mart)와 Sqoop export → MySQL",
    summary: "웹이 읽을 결과를 MySQL로 내보낸다. 수업 Sqoop export 예제와 같은 구조다.",
    code: "sqoop export \\\n  --connect jdbc:mysql://localhost/waterpulse_web \\\n  --username <VM 계정> -P \\\n  --table forecast \\\n  --export-dir /data/waterpulse/mart/forecast_csv \\\n  --input-fields-terminated-by ',' \\\n  --update-key damcode,ts --update-mode allowinsert",
    table: { head: ["mart 표", "한 줄", "쓰는 화면"],
      rows: [["forecast", "댐 × 시각: 3·6·12시간 뒤 예측 유입", "두 화면 공통"],
        ["release", "댐 × 시각: 최소 방류, 24시간 비우기 방류, 12시간 뒤 예상 수위", "방류 계산기"],
        ["alert", "댐 × 시각: 정상·경계·위험, 이유", "재난 상황판"],
        ["lag_events", "큰비 사건 × 댐: 반응 시간, 최대 유입", "근거 화면"],
        ["quality", "댐·관측소: 빈칸·이상값 비율", "근거 화면"]] },
    traps: ["export할 MySQL 표는 미리 만들어 둬야 한다.", "Sqoop export는 Parquet보다 텍스트(CSV) 폴더가 쉽다 → Spark가 mart를 CSV로도 한 벌 쓴다."] },

  // ───────────── 5. 분석 ─────────────
  { id: "A-1", group: "s5", status: "done", title: "반응 시간 (비교 분석) + 20년 추세",
    summary: "비가 가장 많이 온 시각부터 댐 유입이 가장 많은 시각까지의 시간. 큰비 사건마다 재서 댐별 가운데 값을 낸다. 유역이 넓을수록 느린지 비교하고, 20년 동안 변했는지 본다.",
    note: "시뮬레이션 결과: 가운데 값 10시간, 유역 넓이와 순위 상관 ρ=0.89(댐 35곳). 20년 추세는 없음(τ=−0.04, p=0.82). 이 결과는 예측 모델의 '몇 시간 전 비까지 볼지'를 정하는 근거가 된다.",
    steps: ["사건 자르기: 유역 평균 비가 6시간에 20mm 이상인 구간(기준은 바꿔 보며 확인).", "교차상관(비 그래프를 몇 시간 밀었을 때 유입과 가장 닮나)으로 같은 값을 다른 방법으로 확인.", "평균 대신 가운데 값: 튀는 사건 하나에 휘둘리지 않게."],
    links: [L.analyze, L.webIndex] },
  { id: "A-2", group: "s5", status: "doing", title: "유입량 예측 모델 (기본)",
    summary: "3·6·12시간 뒤 '지난 3시간 평균 유입'을 맞힌다. 모델은 '지금보다 얼마나 늘고 줄지'를 배운다.",
    specs: [["모델", "scikit-learn HistGradientBoostingRegressor (빈칸을 그대로 받음), 댐별·시간별로 따로"],
      ["나누기", "시간으로 자른다: 앞 해로 학습, 뒤 해로 시험(섞으면 미래를 미리 본 셈). 큰비 되감기는 그 해를 뺀 해로만 학습"],
      ["기준선", "'3·6·12시간 뒤에도 지금 그대로' — 아무것도 안 배운 예측"],
      ["채점", "평균 절대 오차(MAE), 기준선 대비 개선률 skill = 1 − 모델 MAE / 기준선 MAE, 큰물(상위 시간)만 따로"],
      ["역할 분담", "Spark: 학습표(수백만 행)까지 만든다 · Python: 줄어든 표로 학습·채점(과제가 'any analysis tool… e.g., Python' 허용)"]],
    note: "시뮬레이션: 6시간 뒤 +10%, 큰물 때 +17%. 물이 두 배 넘게 불 때는 실제의 68~45%로 낮게 나온다." },
  { id: "A-3", group: "s5", status: "todo", title: "정확도 올리기: 관측소(15099115)·ASOS(15057210) 단계 실험", due: "2026-11-16",
    summary: "입력을 한 묶음씩 더하면서 같은 시험 기간·같은 채점으로 잰다. 무엇이 얼마나 도움이 되는지 숫자로 남기는 것 자체가 '분석의 깊이'다.",
    table: { head: ["단계", "입력", "기대", "근거"],
      rows: [["M0 기준선", "지금 그대로", "—", "비교의 바닥"],
        ["M1 댐만", "댐 유입·강우·저수율·달력", "시뮬레이션 skill 약 0.10~0.22", "실측"],
        ["M2 + 상류 관측소", "상류 평균 강우, 강 수위 변화, 강 유량", "개선. 3댐에서 skill +1~5%p, 큰물 때 더 큼(대청 12시간 0.15→0.25)", "실측(3댐)"],
        ["M3 + ASOS", "ASOS 강우, 최근 3·7·30일 비, 기온·습도·적설", "작게 개선 예상. 관측소 없는 댐(영주·성덕·보현산)과 땅이 젖어 있던 큰비에서 효과", "가설 → 실험"],
        ["M4 상한", "M3 + 앞으로 12시간 실제로 내린 비(관측값)", "앞으로 올 비를 알면 얼마나 좋아지나의 천장", "가설 → 실험"]] },
    steps: ["대상 댐: 상류 관측소가 많은 댐(소양강·대청·안동·용담·남강·섬진강) + 관측소 없는 댐(영주·성덕·보현산)을 따로 묶어 비교.",
      "M2의 상류 자료는 반응 시간(A-1)만큼 앞선 시점까지 열로 만든다(소양강이면 1~24시간 전).",
      "M3의 '최근 며칠 비'는 땅이 젖은 정도의 대리값이다. 같은 비라도 젖은 땅에서는 물이 더 많이 흘러든다.",
      "M4는 실제 서비스에는 못 쓴다(미래 비를 모름). 'M4 − M3' 차이가 크면 다음 단계는 기상청 강수 예보를 붙이는 것이라는 근거가 된다. 기상청 단기예보는 과거 예보 이력이 없어 되감기 시험이 어렵다는 점도 같이 밝힌다.",
      "결과는 방류 계산기·재난 상황판까지 이어서 잰다: 예측이 좋아지면 '먼저 알림 107번 중 46번'이 몇 번으로 늘어나는가."],
    traps: ["입력을 더할수록 빈칸도 늘어난다(관측소 고장) → 빈칸 비율이 높은 시간은 결과에서 따로 센다.",
      "ASOS와 K-water 강우가 같은 비를 두 번 세는 셈이 될 수 있다 → 중요도(permutation importance)로 겹침을 확인.",
      "시험 기간에 큰비가 적으면 개선이 우연일 수 있다 → 큰물 시간 수(n_high)를 항상 같이 적는다."] },
  { id: "A-4", group: "s5", status: "doing", title: "평소와 다른 순간 찾기 (예측의 덤)",
    summary: "실제 − 예측 오차가 평소 범위(댐별 상위 1%)를 넘으면 표시한다. 먼저 데이터 오류(0 이하, 빈칸, 관측소 고장)를 걸러 진짜 변화와 구분한다.",
    note: "시뮬레이션 예: 소양강 2025-09-17 06~13시, 예측보다 최대 963㎥/s 적게 들어옴." },
  { id: "A-5", group: "s5", status: "doing", title: "방류 계산·경보 채점 검증",
    summary: "G-1·G-2의 숫자를 하둡 결과로 다시 낸다. 오차를 '계산 엔진 탓'과 '예측 탓'으로 나눠 보여 준다.",
    table: { head: ["검증", "시제품 값"],
      rows: [["실제 유입·방류를 넣은 계산 엔진 수위 오차", "평균 7cm"], ["예측 유입 + 실제 방류", "43cm, 물이 불어날 때 78cm(낮게)"], ["'더 내보내라' 답 / 실제 운영", "1.01배 (184번)"], ["운영자 방류 증가를 먼저 알림", "107번 중 46번, 가운데 9.5시간 앞"]] },
    links: [L.dash] },
  { id: "A-6", group: "s5", status: "todo", title: "한계와 예외 정리",
    summary: "최종 채점의 '한계·예외 고려' 항목. 발표 한 장으로 정리한다.",
    steps: ["큰 홍수는 드물다 → 큰물 시간만 따로 채점, 사건 수를 같이 적는다.",
      "유입량은 잰 값이 아니라 계산값 → 처리 전후 결과 비교.",
      "방류는 사람이 정한다 → 방류는 예측 대상이 아니라 입력·채점 기준으로만.",
      "ASOS는 당일 자료가 없다 → 실시간이 아니라 과거 분석용이라고 밝힌다.",
      "함께 움직인다고 원인은 아니다 → '관계가 보인다'로 표현."] },

  // ───────────── 6. 웹 ─────────────
  { id: "W-1", group: "s6", status: "doing", title: "화면 구성",
    table: { head: ["화면", "보는 사람", "핵심 질문"],
      rows: [["방류 계산기", "댐 운영자", "지금 몇 ㎥/s 내보내야 넘치지 않나"], ["재난 상황판", "재난 담당자", "어느 댐이 몇 시간 뒤 위험해지나"], ["분석 근거", "발표·검증", "반응 시간, 예측 정확도, 품질표"]] },
    links: [L.webRelease, L.webAlert, L.webIndex] },
  { id: "W-2", group: "s6", status: "decide", title: "웹이 데이터를 읽는 방법",
    summary: "두 가지 안. 과제 예시와 수업 흐름에 맞는 것은 A다.",
    table: { head: ["안", "흐름", "장점", "단점"],
      rows: [["A (추천)", "Sqoop export → MySQL → 작은 웹 서버(Flask) → 화면", "과제 구조 그림 그대로, VM에서 재현", "서버를 띄워야 볼 수 있음"],
        ["B", "Spark가 JSON으로 내보냄 → 정적 웹(GitHub Pages)", "링크만으로 공유", "DB·웹 서버 구성요소가 빠짐"]] },
    note: "둘 다 할 수 있다: 최종 제출은 A, 팀 공유·발표 링크는 같은 결과를 JSON으로 뽑은 B." },
  { id: "W-3", group: "s6", status: "done", title: "현재 시제품 (로컬 시뮬레이션 데이터)",
    summary: "2020~2025년 실데이터로 큰비 6번을 되감아 볼 수 있다. 숫자 계산은 common.js 한 곳에 있다.",
    links: [L.webRelease, L.webAlert, L.webIndex, L.common] },

  // ───────────── 중간발표 ─────────────
  { id: "M-1", group: "mid", status: "todo", title: "슬라이드 구성안 (약 10분)", due: "2026-10-16",
    table: { head: ["순서", "내용", "시간", "과제 항목"],
      rows: [["1", "표지 · 팀 · 한 문장 목표", "0:30", ""],
        ["2", "문제: 비 → 강 → 댐, 몇 시간 뒤 물이 몰려오나 (2023년 7월 소양강 실제 그래프)", "1:00", "Basic idea"],
        ["3", "데이터셋 5종과 수집량", "1:00", "Basic idea"],
        ["4", "최종 목표 2개: 방류 계산기 · 재난 상황판 (시제품 화면)", "1:00", "Expected results"],
        ["5", "전체 구조 그림", "1:00", "Architecture"],
        ["6", "구성요소별 기능 (수집기·Flume·HDFS·Hive·Impala·Spark·Sqoop·MySQL·웹)", "1:30", "Detailed functionalities"],
        ["7", "중간 결과: VM에서 샘플 적재·조회 화면, 용량·속도 비교, 품질표", "1:30", "Intermediate results"],
        ["8", "분석 계획: 반응 시간 → 예측(관측소·ASOS 단계 실험) → 방류·경보", "1:00", "Planning"],
        ["9", "예외 처리: 찾아낸 데이터 함정과 처리 규칙", "0:45", "Completeness"],
        ["10", "일정·역할", "0:45", "Project plan"]] },
    note: "기존 팀 공유 덱(39장)에서 화면·차트를 가져와 줄인다." },
  { id: "M-2", group: "mid", status: "todo", title: "중간 결과 만들기 (VM 캡처 목록)", due: "2026-10-16",
    steps: ["HDFS: hdfs dfs -ls -R /etl/waterpulse/raw 결과와 Hue 파일 브라우저 화면.",
      "Hive: 원본 표 DDL 실행 화면, SELECT COUNT(*) 결과(행 수가 수집 통계와 맞는지).",
      "Spark: 정제 작업 실행 로그(고친 개수 출력), YARN 화면의 작업 성공.",
      "Impala: 측정 질문 결과와 걸린 시간, JSON vs Parquet 용량(hdfs dfs -du -h).",
      "첫 예측 숫자 1개: 소양강 6시간 뒤, 기준선 MAE vs 모델 MAE.",
      "품질표 1장."] },
  { id: "M-3", group: "mid", status: "todo", title: "영상 녹화", due: "2026-10-18",
    quote: "When you record the video, note that the faces of all presenting team members need to be included. For easy recording for this configuration, Zoom is recommended. A video length of about 10 minutes is recommended, but not strictly restricted.",
    steps: ["Zoom 회의에서 화면 공유 + 발표자 모두 카메라 켜기 → 클라우드/로컬 녹화.", "슬라이드별 발표자를 정하고 대본을 슬라이드 노트에 적는다.", "녹화 후 처음 30초를 다시 보며 얼굴·소리 확인."] },
  { id: "M-4", group: "mid", status: "todo", title: "제출 (10/19 14:00, 늦으면 받지 않음)", due: "2026-10-19",
    quote: "Submit 1) the recorded video, 2) the presentation slide, and 3) supplementary materials (e.g., source codes) to Google Drive (a specific location will be noticed in the e-class)",
    steps: ["e-class에 공지된 Google Drive 위치 확인.", "영상 · 슬라이드(PDF와 원본) · 보충 자료(code 폴더 압축, 샘플 데이터 일부) 업로드.", "10/21 23:59까지 각자 e-class에서 팀원 평가."] },

  // ───────────── 최종발표 ─────────────
  { id: "Z-1", group: "fin", status: "todo", title: "제출물 패키지 (재현 가능하게)", due: "2026-12-06",
    table: { head: ["포함할 것", "내용"],
      rows: [["소스코드", "code/ 전체 + web/"], ["데이터 얻는 법", "인증키 발급 절차(S-3), 수집기 실행법, 받는 데 걸리는 시간"], ["데이터 스냅샷", "받아 둔 원본 일부(키 없이도 재현용)"], ["매뉴얼", "VM에서 순서대로: 적재 → Hive 표 → Spark 정제·분석 → Sqoop export → 웹 실행"]] } },
  { id: "Z-2", group: "fin", status: "doing", title: "문제 분석·디버깅 기록",
    summary: "최종 채점 항목. 이미 겪은 문제를 '증상 → 원인 → 고친 방법 → 전후 숫자'로 모아 둔다.",
    table: { head: ["증상", "원인", "처리"],
      rows: [["정상 응답인데 데이터 0바이트", "페이지 행 수 한도 초과", "400·500·999행으로 페이징"],
        ["9시간 예측 정답이 엉뚱함", "Parquet 행 순서가 시간순 아님", "시각 기준으로 밀기 (0.50 → 0.87)"],
        ["방류 권고가 실제의 1.8배", "'12시간 안에 비우기'를 섞음", "최소 방류와 24시간 비우기를 나눔 (1.01배)"],
        ["경보 '정밀도 39%'", "이미 넘은 시간을 맞힌 것으로 셈", "운영자 방류 증가 선행으로 채점 기준 변경"],
        ["저수량 13만 칸 NULL", "쉼표 문자열을 숫자로 바로 변환", "원본 STRING, Spark에서 쉼표 제거"],
        ["관측소 호출 429", "초당 한도", "3갈래 + 0.3초"]] },
    links: [L.dash, L.sim] },
  { id: "Z-3", group: "fin", status: "todo", title: "최종 영상 (약 15분)", due: "2026-12-07",
    summary: "최종 구현 결과, 구성요소 상세, 문제 분석·디버깅 과정. 발표자 전원 얼굴. 12/9 23:59까지 팀원 평가." },

  // ───────────── 자료실·진행 기록 ─────────────
  { id: "D-1", group: "lib", status: "done", title: "WaterPulse 한눈에 보기 (10/5)",
    summary: "과제 해설, API 5종, 하둡 도구별 뜻과 우리 선택, 분석 방법과 한계.", links: [L.overview] },
  { id: "D-2", group: "lib", status: "done", title: "실데이터 사전 시뮬레이션 보고서 (10/5~6)",
    summary: "694만 행·호출 16,146번·38분 수집, 로컬 Spark 정제, 반응 시간·예측·추세 결과, 용어 풀이.", links: [L.sim] },
  { id: "D-3", group: "lib", status: "done", title: "방류 계산기·재난 상황판 제작 보고서 (10/6)",
    summary: "계산식, 큰비 6번 되감기, 채점 방법 변경 이유, 검증 숫자.", links: [L.dash] },
  { id: "D-4", group: "lib", status: "done", title: "시뮬레이션 코드",
    summary: "collect.py → flume_sim.py → etl_spark.py → analyze.py → scenarios.py. 맥북 로컬 PySpark용이며 VM용으로 옮길 출발점.",
    links: [L.collect, L.flume, L.etl, L.analyze, L.scen, L.probe] },
  { id: "D-5", group: "lib", status: "done", title: "진행 기록",
    table: { head: ["날짜", "한 일"],
      rows: [["09-25", "과제 설명서 받음"], ["10-05", "팀원 제안 WaterPulse로 주제 확정, API 5종 신청·승인·호출 확인, 데이터 함정 6가지 발견"],
        ["10-05", "실데이터 사전 시뮬레이션(로컬): 수집 → 정제 → 분석, 웹 시제품 공개"], ["10-06", "방류 계산기·재난 상황판 추가, 리뷰 반영(9시간 예측 버그, 채점 기준 변경, 방류 권고 1.8배 → 1.01배)"],
        ["10-06", "팀 공유 발표 덱(39장)"], ["10-10", "팀 결정: 최종 목표 = 방류 계산기 + 재난 상황판. ASOS 페이지 한도(999행)·결측 표시 확인. 프로젝트 허브 공개"]] } },
];
